# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=1249, expected_beginning=0x3AC7CF, script=[
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC7CF"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=179, y=162, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0465_TENTACLES_RIGHT, sequence=5, priority=2, vram_address=0x7600, palette_row=12, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Jmp(["command_0x3AC4E2"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC7E7"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=212, y=96, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0472_KING_CALAMARI, sequence=0, priority=2, vram_address=0x7800, palette_row=14, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=KINGCALAMARIEnemy, position=1, bit_7=True),
	Jmp(["command_0x3AC475"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=-32, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3AC803"),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A81B0"]),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0001_MARIO_JUMP_FRONT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	SpriteSequence(sequence=9, mirror=True),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=-65, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	VisibilityOff(unknown_byte=0x01),
	Jmp(["command_0x3AA833"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3AC862"),
	RunSubroutine(["command_0x3A7725"]),
	VisibilityOff(unknown_byte=0x01),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=168, y=144, z=0, set_x=True, set_y=True, set_z=True),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0001_MARIO_JUMP_FRONT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	VisibilityOn(unknown_byte=0x01),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=64, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SetSequenceSpeed(3),
	SpriteSequence(sequence=8),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=8),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	SetSequenceSpeed(1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=0, looping_on=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=110),
	Jmp(["command_0x3AB7CC"]),
	SetAMEM8BitToRAMRelative7E(0x60, 0x7E0000, identifier="command_0x3AC8F3"),
	SetAMEMBits(0x60, [7]),
	SetRAMRelative7EToAMEM8Bit(0x7E0000, 0x60),
	RunSubroutine(["command_0x3A755E"]),
	RunSubroutine(["command_0x3A7725"]),
	RunSubroutine(["command_0x3A86A7"]),
	PlaySound(sound=S0092_SPEAR_RAIN_SINGLE),
	ResetTargetMappingMemory(),
	MoveObject(speed=65, start_position=-1025, end_position=-4097, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3AC020"]),
	ClearAMEM8Bit(0x60),
	SetAbsolute7EToAMEM8Bit(0x7EE00D, 0x60),
	SetAMEM8BitToAbsolute7E(0x60, 0x7EFA00),
	IncAMEM8Bit(0x60),
	SetAMEM8BitToConst(0x61, 1),
	UnknownCommand(bytearray([0x16]), identifier="command_0x3AC925"),
	Pause1Frame(),
	JmpIfAMEM8BitEqualsAbsolute7E(0x61, 0x7EE00D, ["command_0x3AC933"]),
	JmpIfAMEM8BitNotEqualsAbsolute7E(0x60, 0x7EFA00, ["command_0x3AC925"]),
	ResetTargetMappingMemory(identifier="command_0x3AC933"),
	MoveObject(speed=65, start_position=1024, end_position=4096, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A7253"]),
	RunSubroutine(["command_0x3A71DA"]),
	RunSubroutine(["command_0x3A7541"]),
	SetAMEM8BitToConst(0x60, 8),
	SetRAMRelative7EToAMEM8Bit(0x7E0040, 0x60),
	SetAMEM16BitToConst(0x60, 3),
	SetRAMRelative7EToAMEM16Bit(0x7E0043, 0x60),
	UnknownCommand(bytearray([0x6D])),
	SetAMEM8BitToRAMRelative7E(0x60, 0x7E0000),
	ClearAMEMBits(0x60, [7]),
	SetRAMRelative7EToAMEM8Bit(0x7E0000, 0x60),
	ClearAMEM8Bit(0x60),
	SetAbsolute7EToAMEM8Bit(0x7EE008, 0x60),
	ReturnSpriteQueue(),
	RunSubroutine(["command_0x3A756A"], identifier="command_0x3AC968"),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(identifier="command_0x3AC96E"),
	Jmp(["command_0x3AA879"]),
	SpriteSequence(sequence=2, identifier="command_0x3AC972"),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	Jmp(["command_0x3ABA03"]),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3AC97D"),
	DisplayMessage(ATTACK_NAME, 96),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 97),
	RunSubroutine(["command_0x3A733C"]),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A758E"]),
	RunSubroutine(["command_0x3A7751"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 99),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7359"]),
	PauseScriptUntilDialogClosed(),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A75A6"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	Jmp(["command_0x3AC96E"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC9CA"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	RunSubroutine(["command_0x3A733C"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=176, y=136, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DisplayMessage(ATTACK_NAME, 95),
	SpriteSequence(sequence=3, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A7582"]),
	RunSubroutine(["command_0x3A7746"]),
	DisplayMessage(ATTACK_NAME, 98),
	SpriteSequence(sequence=3, looping_on=True, mirror=True),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7359"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A759A"]),
	RunSubroutine(["command_0x3A775C"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	DisplayMessage(ATTACK_NAME, 100),
	RunSubroutine(["command_0x3A71EE"]),
	ResetSpriteSequence(),
	Jmp(["command_0x3AAAF7"]),
	SpriteSequence(sequence=2, identifier="command_0x3ACA38"),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A756A"]),
	RunSubroutine(["command_0x3A7730"]),
	SpriteSequence(sequence=3, looping_on=True),
	RunSubroutine(["command_0x3A771A"], identifier="command_0x3ACA48"),
	ResetSpriteSequence(),
	ReturnSpriteQueue(),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3ACA4D"),
	DisplayMessage(ATTACK_NAME, 96),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 101),
	RunSubroutine(["command_0x3A733C"]),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A758E"]),
	RunSubroutine(["command_0x3A7751"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 102),
	RunSubroutine(["command_0x3A733C"]),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75A6"]),
	RunSubroutine(["command_0x3A7767"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 104),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75BE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 105),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7359"]),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A7576"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 106),
	RunSubroutine(["command_0x3A75CC"]),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=4608, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 107),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7373"]),
	PauseScriptUntilDialogClosed(),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A81D8"]),
	RunSubroutine(["command_0x3A7265"]),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A75D8"]),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-769, end_position=-769, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=384, end_position=384, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60, identifier="command_0x3ACB05"),
	ResetObjectMappingMemory(identifier="command_0x3ACB09"),
	Jmp(["command_0x3AA879"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3ACB0D"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	RunSubroutine(["command_0x3A733C"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=176, y=136, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DisplayMessage(ATTACK_NAME, 95),
	SpriteSequence(sequence=3, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A7582"]),
	RunSubroutine(["command_0x3A7746"]),
	DisplayMessage(ATTACK_NAME, 98),
	SpriteSequence(sequence=3, looping_on=True, mirror=True),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7359"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A759A"]),
	RunSubroutine(["command_0x3A775C"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	DisplayMessage(ATTACK_NAME, 103),
	SpriteSequence(sequence=3, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75B2"]),
	RunSubroutine(["command_0x3A7772"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A777D"]),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A7788"]),
	DisplayMessage(ATTACK_NAME, 108),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A81D8"]),
	RunSubroutine(["command_0x3A7265"]),
	SpriteSequence(sequence=0, looping_on=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-769, end_position=-769, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=384, end_position=384, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	Jmp(["command_0x3ABE85"]),
	SpriteSequence(sequence=3, looping_on=True, identifier="command_0x3ACBC6"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
	Jmp(["command_0x3AC96E"]),
	SpriteSequence(sequence=3, looping_on=True, identifier="command_0x3ACBCF"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
	Jmp(["command_0x3ABA38"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3ACBD8"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=199, y=80, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0510_CANDLE, sequence=1, priority=2, vram_address=0x7E00, palette_row=14, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=CANDLEEnemy, position=1, bit_7=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=2, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=3, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=4, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=5, looping_on=True),
	DisplayMessage(ATTACK_NAME, 137),
	Jmp(["command_0x3AAAF7"]),
	ClearAMEM8Bit(0x69, identifier="command_0x3ACC0F"),
	UnknownCommand(bytearray([0x16]), identifier="command_0x3ACC11"),
	Pause1Frame(),
	SetAMEM8BitToAbsolute7E(0x68, 0x7EE007),
	JmpIfAMEM8BitEqualsAMEM(amem=0x68, source_amem=0x69, upper=0x60, destinations=["command_0x3ACC11"]),
	SetAMEM8BitToAMEM(amem=0x69, source_amem=0x68, upper=0x60),
	JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3ACC48"]),
	JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3ACC4D"]),
	JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3ACC52"]),
	JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3ACC57"]),
	JmpIfAMEM8BitEqualsConst(0x68, 4, ["command_0x3ACC5C"]),
	JmpIfAMEM8BitEqualsConst(0x68, 5, ["command_0x3ACC61"]),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=5, looping_on=True, identifier="command_0x3ACC48"),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=4, looping_on=True, identifier="command_0x3ACC4D"),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=3, looping_on=True, identifier="command_0x3ACC52"),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=2, looping_on=True, identifier="command_0x3ACC57"),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=1, looping_on=True, identifier="command_0x3ACC5C"),
	Jmp(["command_0x3ACC11"]),
	SpriteSequence(sequence=6, looping_on=True, identifier="command_0x3ACC61"),
	Jmp(["command_0x3ACC11"])
])
