# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=582, expected_beginning=0x3AA6A7, script=[
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=0, store_to_vram=True, looping=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, identifier="command_0x3AA6A7"),
	RunSubroutine(["command_0x3A8296"]),
	RunSubroutine(["command_0x3A72DD"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=5, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	SpriteSequence(sequence=5, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	DisplayMessage(ATTACK_NAME, 2),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A759A"]),
	PlaySound(sound=S0080_WALLOP_1),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A7767"]),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_7=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A775C"]),
	SpriteSequence(sequence=3, looping_off=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-385, end_position=512, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	ResetObjectMappingMemory(),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A771A"]),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_on=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-193, end_position=-193, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=32, end_position=32, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	ResetObjectMappingMemory(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=6, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	RunSubroutine(["command_0x3A758E"]),
	DisplayMessage(ATTACK_NAME, 3),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	PauseScriptUntilDialogClosed(),
	AddItemToKeyItemInventory(RareFrogCoinItem),
	RunSubroutine(["command_0x3A756A"]),
	SpriteSequence(sequence=1, looping_off=True),
	RunSubroutine(["command_0x3A7541"], identifier="command_0x3AA75F"),
	ReturnSpriteQueue(),
	SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3AA763"),
	RunSubroutine(["command_0x3A7751"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=22),
	SpriteSequence(sequence=2, looping_off=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-385, end_position=512, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	ResetObjectMappingMemory(),
	SpriteSequence(sequence=0, looping_off=True),
	DisplayMessage(ATTACK_NAME, 4),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A8296"]),
	RunSubroutine(["command_0x3A7265"]),
	RunSubroutine(["command_0x3A75A6"]),
	PlaySound(sound=S0039_CLAW),
	SpriteSequence(sequence=7, looping_off=True),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A736D"]),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=0, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
	ResetObjectMappingMemory(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0496_CROCO_ST_TIME, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	DisplayMessage(ATTACK_NAME, 5),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A82D2"]),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A72EF"]),
	RunSubroutine(["command_0x3A8214"]),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A72F8"]),
	RunSubroutine(["command_0x3A8322"]),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A730A"]),
	RunSubroutine(["command_0x3A8340"]),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A72F8"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	DisplayMessage(ATTACK_NAME, 6),
	RunSubroutine(["command_0x3A733C"]),
	PauseScriptUntilDialogClosed(),
	SpriteSequence(sequence=8, looping_off=True, mirror=True),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-1025, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=512, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A755E"], identifier="command_0x3AA833"),
	ReturnSpriteQueue(),
	DisplayMessage(ATTACK_NAME, 61, identifier="command_0x3AA837"),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A8160"]),
	PlaySound(sound=S0011_SWOOSH_RUN_AWAY),
	RunSubroutine(["command_0x3A7277"]),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1),
	RunSubroutine(["command_0x3A756A"]),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=49, start_position=-1537, end_position=1536, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A773B"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	RunSubroutine(["command_0x3A71DA"], identifier="command_0x3AA86B"),
	Jmp(["command_0x3AA833"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AA871"),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A771A"], identifier="command_0x3AA879"),
	ReturnSpriteQueue(),
	DisplayMessage(ATTACK_NAME, 62, identifier="command_0x3AA87D"),
	RunSubroutine(["command_0x3A733C"]),
	PauseScriptUntilDialogClosed(),
	SpriteSequence(sequence=8, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A756A"]),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-1025, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PlaySound(sound=S0004_JUMP),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=512, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=81, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A773B"]),
	Jmp(["command_0x3AA833"])
])
