# R294_UNMAPPED_HOUSE_ROOM
# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.levels.classes import ObjectType, EventInitiator, PostBattleBehaviour, Direction, EdgeDirection, ExitType, BufferType, BufferSpace, VramStore, ShadowSize
from smrpgpatchbuilder.datatypes.levels.classes import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from smrpgpatchbuilder.datatypes.overworld_scripts.arguments.directions import *
from . import npcs
from ..variables.room_names import *
from ..variables.overworld_area_names import *
from ..variables.music_names import *
from ..variables.event_script_names import *
from ..variables.action_script_names import *
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=False,
        extra_sprite_buffer_size=0,
        buffers = [
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=M0039_MARRYMORE,
    entrance_event=E3010_CLONE_RESERVED,
    events=[
        Event(
            event=E3008_CLONE_RESERVED,
            x=16,
            y=81,
            z=0,
            f=EdgeDirection.SOUTHWEST,
            height=4,
            length=4,
            nw_se_edge_active=False,
            ne_sw_edge_active=False,
            byte_8_bit_4=False,
        ),
        Event(
            event=E3009_CLONE_RESERVED,
            x=8,
            y=99,
            z=0,
            f=EdgeDirection.SOUTHWEST,
            height=0,
            length=2,
            nw_se_edge_active=False,
            ne_sw_edge_active=False,
            byte_8_bit_4=False,
        ),
    ],
    objects=[
        RegularNPC( # 0
            npc=npcs.BUNDT_OBJECT_NPC,
            initiator=EventInitiator.NONE,
            event_script=E0000_EMPTY,
            action_script=A0015_DO_NOTHING,
            visible=True,
            x=20,
            y=78,
            z=0,
            z_half=False,
            direction=SOUTHWEST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=False,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=False,
            byte7_upper2=3,
        ),
        RegularNPC( # 1
            npc=npcs.TORTE_NPC_2,
            initiator=EventInitiator.NONE,
            event_script=E0000_EMPTY,
            action_script=A0000_DO_NOTHING,
            visible=True,
            x=19,
            y=78,
            z=0,
            z_half=False,
            direction=SOUTHWEST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=False,
            byte7_upper2=3,
        ),
        RegularClone( # 2
            npc=npcs.TORTE_NPC_2,
            event_script=E0000_EMPTY,
            action_script=A0000_DO_NOTHING,
            visible=True,
            x=19,
            y=79,
            z=0,
            z_half=False,
            direction=SOUTHWEST,
        ),
        RegularNPC( # 3
            npc=npcs.TOADSTOOL_WALKING_DOWN_LEFT_NPC,
            initiator=EventInitiator.NONE,
            event_script=E0000_EMPTY,
            action_script=A0000_DO_NOTHING,
            visible=True,
            x=3,
            y=55,
            z=0,
            z_half=False,
            direction=SOUTHWEST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=False,
            byte7_upper2=3,
        ),
        RegularClone( # 4
            npc=npcs.MALLOW_WALKING_DOWN_LEFT_NPC,
            event_script=E0000_EMPTY,
            action_script=A0000_DO_NOTHING,
            visible=True,
            x=1,
            y=55,
            z=0,
            z_half=False,
            direction=SOUTHWEST,
        ),
    ]
)
