# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=6419, expected_beginning=0x355FA1, script=[
	DefineObjectQueue(["command_0x355FA7", "command_0x355FC7", "command_0x355FE4"], identifier="command_0x355FA1"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x355FA7"),
	SetAMEM16BitToConst(0x6E, 65535),
	SetAMEMToAMEM16Bit(dest_amem=0x6C, upper=0x00, amem=0x6E),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=1, priority=0, vram_address=0x6200, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35812B"], identifier="command_0x355FC1"),
	RemoveObject(),
	DisableSpritesOnSubscreen(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x355FC7"),
	SetAMEM16BitToConst(0x6E, 65535),
	SetAMEMToAMEM16Bit(dest_amem=0x6C, upper=0x00, amem=0x6E),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=1, priority=0, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x355FC1"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x355FE4"),
	SetAMEM16BitToConst(0x6E, 65535),
	SetAMEMToAMEM16Bit(dest_amem=0x6C, upper=0x00, amem=0x6E),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=1, priority=0, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x355FC1"]),
	DefineObjectQueue(["command_0x356003"], identifier="command_0x356001"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356003"),
	SetAMEM8BitToConst(0x61, 129),
	SetAMEM8BitToConst(0x62, 32),
	SetAMEM8BitToUnknownShort(amem=0x63, type=0x8, value=0x0001),
	SetAMEM8BitToConst(0x64, 1),
	SetAMEM8BitToConst(0x65, 0),
	SetAMEM8BitToConst(0x66, 8),
	SetAMEM16BitToConst(0x67, 25088),
	SetAMEM16BitToConst(0x6E, 65535),
	SetAMEMToAMEM16Bit(dest_amem=0x6C, upper=0x00, amem=0x6E),
	EnableSpritesOnSubscreen(),
	UnknownCommand(bytearray([0x17])),
	RunSubroutine(["command_0x35811C"]),
	RemoveObject(),
	DisableSpritesOnSubscreen(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x356039"], identifier="command_0x356037"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356039"),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x60),
	SetAMEM16BitToConst(0x60, 7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356240"]),
	RunSubroutine(["command_0x352538"]),
	RunSubroutine(["command_0x35258E"]),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x356056"], identifier="command_0x356054"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356056"),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x35606D"], identifier="command_0x35606B"),
	SetAMEM60ToCurrentTarget(identifier="command_0x35606D"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x35357F"]),
	RunSubroutine(["command_0x352522"]),
	DefineObjectQueue(["command_0x35607E"], identifier="command_0x35607C"),
	SetAMEM60ToCurrentTarget(identifier="command_0x35607E"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0517_BOMB_EXPLOSION, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x3560A0"], identifier="command_0x35609E"),
	SetAMEM60ToCurrentTarget(identifier="command_0x3560A0"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	PlaySound(sound=S0122_POISONED),
	NewSpriteAtCoords(sprite_id=SPR0515_GREEN_EXPLOSION, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x3560C4"], identifier="command_0x3560C2"),
	SetAMEM60ToCurrentTarget(identifier="command_0x3560C4"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0526_YELLOW_MIST_STEAM, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x3560F5"], identifier="command_0x3560F3"),
	SetAMEM60ToCurrentTarget(identifier="command_0x3560F5"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-32, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0537_MUSHROOM_SPORES, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	PlaySound(sound=S0115_TRANSFORM),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x356128"], identifier="command_0x356126"),
	SetAMEM60ToCurrentTarget(identifier="command_0x356128"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=3, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	SetAMEM16BitToConst(0x60, 20),
	RunSubroutine(["command_0x352495"]),
	PlaySound(sound=S0115_TRANSFORM),
	RunSubroutine(["command_0x352522"]),
	DefineObjectQueue(["command_0x356149"], identifier="command_0x356147"),
	SetAMEM60ToCurrentTarget(identifier="command_0x356149"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-24, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	PlaySound(sound=S0134_BOO_DISAPPEARS),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0793_BIG_PINK_HEART, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=1),
	PauseScriptUntilSpriteSequenceDone(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x356171"], identifier="command_0x35616F"),
	SetAMEM60ToCurrentTarget(identifier="command_0x356171"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	PlaySound(sound=S0037_MONSTER_ITEM_TOSS),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0801_SLEEP_ZZZ_S, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x3561A4"], identifier="command_0x3561A2"),
	SetAMEM60ToCurrentTarget(identifier="command_0x3561A4"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-32, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x352522"]),
	PlaySound(sound=S0029_FIRE_SHOOT),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0551_MUTE_BALLOON, sequence=3, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x3561D9", "command_0x356208"], identifier="command_0x3561D5"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=-16, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3561D9"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0810_WHITE_PIXEL_DOT, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=1),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x60),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356240"]),
	RunSubroutine(["command_0x352538"]),
	PauseScriptUntilSpriteSequenceDone(),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x356208"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0811_EMPTY, sequence=0, priority=0, vram_address=0x6200, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=1),
	VisibilityOn(unknown_byte=0x01),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x60),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356240"]),
	RunSubroutine(["command_0x352538"]),
	PauseScriptUntilSpriteSequenceDone(),
	FadeOutSprite(duration=2),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	VisibilityOff(unknown_byte=0x01),
	DisableSpritesOnSubscreen(),
	RunSubroutine(["command_0x352517"]),
	DefineObjectQueue(["command_0x35625A", "command_0x3563CE", "command_0x35650E", "command_0x356590", "command_0x3565EE", "command_0x356638", "command_0x3566AD", "command_0x356739", "command_0x356814", "command_0x356901", "command_0x356950", "command_0x356988", "command_0x356A56"], identifier="command_0x356240"),
	DefineObjectQueue(["command_0x356266", "command_0x356298", "command_0x3562DE", "command_0x356313", "command_0x356348", "command_0x356399"], identifier="command_0x35625A"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356266"),
	NewSpriteAtCoords(sprite_id=SPR0532_BLUE_SPARK, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"], identifier="command_0x35627F"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x35627F"]),
	Pause1Frame(identifier="command_0x35628F"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x35628F"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=8, set_x=True, set_y=True, set_z=True, identifier="command_0x356298"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0533_YELLOW_SPARK, sequence=0, priority=0, vram_address=0x6200, palette_row=8, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x356ADF"], identifier="command_0x3562B9"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x356ADF"]),
	Pause1Frame(),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 10, ["command_0x3562B9"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
	FadeOutSprite(duration=2),
	VisibilityOff(unknown_byte=0x01),
	Pause1Frame(identifier="command_0x3562D3"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 20, ["command_0x3562D3"]),
	DisableSpritesOnSubscreen(identifier="command_0x3562DA"),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=254, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3562DE"),
	NewSpriteAtCoords(sprite_id=SPR0532_BLUE_SPARK, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x64),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x3562F9"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 24, ["command_0x3562F9"]),
	Pause1Frame(identifier="command_0x356309"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 24, ["command_0x356309"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=4, y=160, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356313"),
	NewSpriteAtCoords(sprite_id=SPR0532_BLUE_SPARK, sequence=0, priority=3, vram_address=0x6600, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x356ADF"], identifier="command_0x35632E"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x35632E"]),
	Pause1Frame(identifier="command_0x35633E"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x35633E"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=253, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356348"),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 11),
	PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x35638F"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x35638F"]),
	Jmp(["command_0x35403A"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=254, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356399"),
	NewSpriteAtCoords(sprite_id=SPR0535_RED_SPARK, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x64),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x3563B4"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 24, ["command_0x3563B4"]),
	Pause1Frame(identifier="command_0x3563C4"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 24, ["command_0x3563C4"]),
	Jmp(["command_0x356AD9"]),
	DefineObjectQueue(["command_0x3563D8", "command_0x356449", "command_0x3564C9", "command_0x35650E", "command_0x35650E"], identifier="command_0x3563CE"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=4, y=256, z=8, set_x=True, set_y=True, set_z=True, identifier="command_0x3563D8"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL, sequence=1, priority=0, vram_address=0x6600, palette_row=8, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	FadeOutEffect(duration=1),
	SpriteSequence(sequence=2, looping_on=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	FadeOutSprite(duration=2),
	VisibilityOff(unknown_byte=0x01),
	Pause1Frame(identifier="command_0x35643F"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 8, ["command_0x35643F"]),
	DisableSpritesOnSubscreen(),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=8, set_x=True, set_y=True, set_z=True, identifier="command_0x356449"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL, sequence=0, priority=0, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 3),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0795_LIGHT_GREEN_STARS, sequence=0, store_to_vram=True, looping=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=18, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x356ADF"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0796_LIGHT_ORANGE_STARS, sequence=0, store_to_vram=True, looping=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x3564BF"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 18, ["command_0x3564BF"]),
	Jmp(["command_0x3562DA"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=6, y=200, z=8, set_x=True, set_y=True, set_z=True, identifier="command_0x3564C9"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL, sequence=0, priority=0, vram_address=0x6200, palette_row=8, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x356ADF"], identifier="command_0x3564EA"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x356ADF"]),
	Pause1Frame(),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x3564EA"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
	FadeOutSprite(duration=2),
	VisibilityOff(unknown_byte=0x01),
	Pause1Frame(identifier="command_0x356504"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x356504"]),
	Jmp(["command_0x3562DA"]),
	DefineObjectQueue(["command_0x356516", "command_0x356516", "command_0x356516", "command_0x356516"], identifier="command_0x35650E"),
	ResetTargetMappingMemory(identifier="command_0x356516"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=240, z=0, set_x=True, set_y=True, set_z=True),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0790_PLASM_WATER_DROPLET_BLUE_GREEN, sequence=1, priority=0, vram_address=0x6200, palette_row=8, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	VisibilityOn(unknown_byte=0x01),
	PlaySound(sound=S0068_RECOVER_DRINK),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 2),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	Pause1Frame(identifier="command_0x356586"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 10, ["command_0x356586"]),
	Jmp(["command_0x3562DA"]),
	DefineObjectQueue(["command_0x356592"], identifier="command_0x356590"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356592"),
	NewSpriteAtCoords(sprite_id=SPR0804_GUNK_BALL_INK_BLAST, sequence=5, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"], identifier="command_0x3565AD"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 10, ["command_0x3565AD"]),
	SpriteSequence(sequence=6),
	ClearAMEM8Bit(0x64),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"], identifier="command_0x3565C1"),
	RunSubroutine(["command_0x358117"]),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 20, ["command_0x3565C1"]),
	SpriteSequence(sequence=7),
	ClearAMEM8Bit(0x64),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"], identifier="command_0x3565D4"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 30, ["command_0x3565D4"]),
	Pause1Frame(identifier="command_0x3565E4"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 60, ["command_0x3565E4"]),
	Jmp(["command_0x356AD9"]),
	DefineObjectQueue(["command_0x3565F8", "command_0x3565F8", "command_0x356638", "command_0x356638", "command_0x356638"], identifier="command_0x3565EE"),
	ResetTargetMappingMemory(identifier="command_0x3565F8"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=240, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0532_BLUE_SPARK, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	MoveObject(speed=1, start_position=512, end_position=0, apply_to_z=True, should_set_speed=True),
	ClearAMEM8Bit(0x67),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x35661D"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 16, ["command_0x35661D"]),
	Pause1Frame(identifier="command_0x35662D"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 16, ["command_0x35662D"]),
	ResetObjectMappingMemory(),
	Jmp(["command_0x356ADC"]),
	DefineObjectQueue(["command_0x35663E", "command_0x356678", "command_0x356678"], identifier="command_0x356638"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35663E"),
	NewSpriteAtCoords(sprite_id=SPR0782_DIAMOND_SAW_SNOWFLAKE, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 4),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x357D34"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=112),
	FadeOutSprite(duration=2),
	VisibilityOff(unknown_byte=0x01),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	Pause1Frame(identifier="command_0x35666E"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 2, ["command_0x35666E"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356678"),
	NewSpriteAtCoords(sprite_id=SPR0544_SMALL_PINK_PETAL, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=28, destinations=["command_0x356ADF"], identifier="command_0x356693"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 32, ["command_0x356693"]),
	Pause1Frame(identifier="command_0x3566A3"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 32, ["command_0x3566A3"]),
	Jmp(["command_0x356AD9"]),
	DefineObjectQueue(["command_0x3566B5", "command_0x35670C", "command_0x35671B", "command_0x35672A"], identifier="command_0x3566AD"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3566B5"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0524_EMPTY, sequence=1, priority=0, vram_address=0x6400, palette_row=8, overwrite_palette=True, overlap_all_sprites=True),
	FadeInSprite(duration=2),
	VisibilityOn(unknown_byte=0x01),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x3566D6"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 12, ["command_0x3566D6"]),
	SpriteSequence(sequence=2),
	ClearAMEM8Bit(0x64),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x3566EA"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x3566EA"]),
	FadeOutSprite(duration=2),
	VisibilityOff(unknown_byte=0x01),
	UnknownCommand(bytearray([0x74, 0x00, 0x04])),
	Pause1Frame(identifier="command_0x356702"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 18, ["command_0x356702"]),
	Jmp(["command_0x3562DA"]),
	RunSubroutine(["command_0x3526B5"], identifier="command_0x35670C"),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x3526B5"], identifier="command_0x35671B"),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x3526B5"], identifier="command_0x35672A"),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6600, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x356741", "command_0x356778", "command_0x3567AD", "command_0x3567E2"], identifier="command_0x356739"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356741"),
	NewSpriteAtCoords(sprite_id=SPR0792_BLACK_ROCK, sequence=3, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x35676E"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x35676E"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=2, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356778"),
	NewSpriteAtCoords(sprite_id=SPR0792_BLACK_ROCK, sequence=2, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"], identifier="command_0x356793"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x356793"]),
	Pause1Frame(identifier="command_0x3567A3"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x3567A3"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=2, y=232, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3567AD"),
	NewSpriteAtCoords(sprite_id=SPR0792_BLACK_ROCK, sequence=1, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x67),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 0),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x358126"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x358126"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x3567D8"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 3, ["command_0x3567D8"]),
	Jmp(["command_0x356ADC"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3567E2"),
	NewSpriteAtCoords(sprite_id=SPR0531_BLACK_ROLLING_COAL_ROCK, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	ClearAMEM8Bit(0x64),
	SetAMEM16BitToConst(0x60, 5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"], identifier="command_0x3567FD"),
	Pause1Frame(),
	IncAMEM8Bit(0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 12, ["command_0x3567FD"]),
	Pause1Frame(identifier="command_0x35680A"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x35680A"]),
	Jmp(["command_0x35401A"]),
	DefineObjectQueue(["command_0x35681A", "command_0x356882", "command_0x356901"], identifier="command_0x356814"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35681A"),
	NewSpriteAtCoords(sprite_id=SPR0809_BLUE_MUSIC_NOTE, sequence=0, priority=0, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ShineEffect(colour_count=8, starting_colour_index=1, glow_duration=1, east=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 6),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	SpriteSequence(sequence=1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=2),
	Pause1Frame(identifier="command_0x356877"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x356877"]),
	UnknownCommand(bytearray([0x81]), identifier="command_0x35687E"),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356882"),
	EnableSpritesOnSubscreen(),
	NewSpriteAtCoords(sprite_id=SPR0809_BLUE_MUSIC_NOTE, sequence=0, priority=0, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ShineEffect(colour_count=8, starting_colour_index=1, glow_duration=1, east=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 6),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=18, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=24, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=26, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=28, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=30, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=18, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=0),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=2),
	Pause1Frame(identifier="command_0x3568F6"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x3568F6"]),
	DisableSpritesOnSubscreen(),
	Jmp(["command_0x35687E"]),
	DefineObjectQueue(["command_0x356903"], identifier="command_0x356901"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356903"),
	NewSpriteAtCoords(sprite_id=SPR0785_SPRITZ_BOMB, sequence=1, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0088_TICKING_BOMB),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 6),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x357BA6"]),
	StopCurrentSoundEffect(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0517_BOMB_EXPLOSION, sequence=0, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0012_BOMB_EXPLOSION),
	Pause1Frame(identifier="command_0x356946"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x356946"]),
	Jmp(["command_0x356AD9"]),
	DefineObjectQueue(["command_0x356952"], identifier="command_0x356950"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356952"),
	RunSubroutine(["command_0x352EED"]),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 7),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x358126"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x358126"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x358126"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x35697E"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x35697E"]),
	Jmp(["command_0x356AD9"]),
	DefineObjectQueue(["command_0x356990", "command_0x3569C8", "command_0x356A00", "command_0x356A2B"], identifier="command_0x356988"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356990"),
	NewSpriteAtCoords(sprite_id=SPR0192_COIN, sequence=1, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 9),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x357BA6"]),
	SpriteSequence(sequence=2),
	Pause1Frame(identifier="command_0x3569BE"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x3569BE"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3569C8"),
	NewSpriteAtCoords(sprite_id=SPR0193_SMALL_COIN, sequence=1, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x67),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 9),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x356ADF"]),
	RunSubroutine(["command_0x357BA6"]),
	SpriteSequence(sequence=2),
	Pause1Frame(identifier="command_0x3569F6"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x3569F6"]),
	Jmp(["command_0x356ADC"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356A00"),
	NewSpriteAtCoords(sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x356A21"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 2, ["command_0x356A21"]),
	Jmp(["command_0x35401A"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356A2B"),
	NewSpriteAtCoords(sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD, sequence=1, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x67),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 10),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	Pause1Frame(identifier="command_0x356A4C"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 2, ["command_0x356A4C"]),
	Jmp(["command_0x35403A"]),
	DefineObjectQueue(["command_0x356A5A", "command_0x356A93"], identifier="command_0x356A56"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356A5A"),
	NewSpriteAtCoords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=5, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x68),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 9),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
	SpriteSequence(sequence=4),
	Pause1Frame(identifier="command_0x356A89"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x356A89"]),
	Jmp(["command_0x356AD9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356A93"),
	NewSpriteAtCoords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=5, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM8Bit(0x67),
	ClearAMEM8Bit(0x69),
	SetAMEM16BitToConst(0x60, 9),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x356ADF"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x356ADF"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
	SpriteSequence(sequence=4),
	Pause1Frame(identifier="command_0x356AC2"),
	JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x356AC2"]),
	Jmp(["command_0x356ADC"]),
	SetAMEM8BitToOMEMMain(amem=0x69, omem=0x69, identifier="command_0x356ACC"),
	IncAMEM8Bit(0x69),
	SetOMEMMainToAMEM8Bit(omem=0x69, amem=0x69),
	RemoveObject(),
	ResetObjectMappingMemory(),
	ReturnObjectQueue(),
	Jmp(["command_0x354D48"], identifier="command_0x356AD9"),
	Jmp(["command_0x354D64"], identifier="command_0x356ADC"),
	DefineObjectQueue(["command_0x356AF7", "command_0x356BA9", "command_0x356BB3", "command_0x356BF9", "command_0x356D30", "command_0x356DB0", "command_0x356E0D", "command_0x357167", "command_0x3571BA", "command_0x3571BC", "command_0x357388", "command_0x357404"], identifier="command_0x356ADF"),
	DefineObjectQueue(["command_0x356B15", "command_0x356B21", "command_0x356B30", "command_0x356B30", "command_0x356B30", "command_0x356B30", "command_0x356B4E", "command_0x356B69", "command_0x356B77", "command_0x356B77", "command_0x356B77", "command_0x356B85", "command_0x356B90", "command_0x356B90", "command_0x356B90"], identifier="command_0x356AF7"),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B15"),
	UnknownCommand(bytearray([0x83, 0x83])),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B21"),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352C00"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20, identifier="command_0x356B29"),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B30"),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352C00"]),
	RunSubroutine(["command_0x357BF4"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	MoveObject(speed=65, start_position=0, end_position=-1025, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B4E"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B69"),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352C38"]),
	RunSubroutine(["command_0x357BA6"], identifier="command_0x356B71"),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B77"),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352DC0"]),
	RunSubroutine(["command_0x352C70"], identifier="command_0x356B7F"),
	Jmp(["command_0x356B71"]),
	RunSubroutine(["command_0x35259A"], identifier="command_0x356B85"),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352D13"]),
	Jmp(["command_0x356B7F"]),
	RunSubroutine(["command_0x352AE5"], identifier="command_0x356B90"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-1025, end_position=-1025, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=512, end_position=512, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356B29"]),
	DefineObjectQueue(["command_0x356BB3", "command_0x356BB3", "command_0x356BB3", "command_0x356BB3", "command_0x356BB3"], identifier="command_0x356BA9"),
	DefineObjectQueue(["command_0x356BBD", "command_0x356BD2", "command_0x356BDD", "command_0x356BE8", "command_0x356BEE"], identifier="command_0x356BB3"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356BBD"),
	UnknownCommand(bytearray([0x83, 0x83]), identifier="command_0x356BC5"),
	RunSubroutine(["command_0x352C53"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	ResetObjectMappingMemory(identifier="command_0x356BCE"),
	Jmp(["command_0x356ACC"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-264, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356BD2"),
	Jmp(["command_0x356BC5"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=-240, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356BDD"),
	Jmp(["command_0x356BC5"]),
	RunSubroutine(["command_0x352640"], identifier="command_0x356BE8"),
	Jmp(["command_0x356BC5"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=-263, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356BEE"),
	Jmp(["command_0x356BC5"]),
	DefineObjectQueue(["command_0x356C11", "command_0x356C29", "command_0x356C46", "command_0x356C63", "command_0x356C78", "command_0x356C8D", "command_0x356CA2", "command_0x356CBF", "command_0x356CD4", "command_0x356CF1", "command_0x356D06", "command_0x356D1B"], identifier="command_0x356BF9"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-264, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C11"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=-257, end_position=-1281, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358126"], identifier="command_0x356C23"),
	Jmp(["command_0x356BCE"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-259, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C29"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=-257, end_position=-1281, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=25, start_position=-129, end_position=-1281, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x356C3B"),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-253, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C46"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=-257, end_position=-1281, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=25, start_position=128, end_position=1280, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x356C58"),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-248, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C63"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=256, end_position=1280, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=6, y=-253, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C78"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=256, end_position=1280, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356C58"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=6, y=-259, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356C8D"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=256, end_position=1280, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356C3B"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-3, y=-262, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356CA2"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=33, start_position=-193, end_position=-1281, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-193, end_position=-1281, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x356CB4"),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356CBF"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=-257, end_position=-1281, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-3, y=-250, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356CD4"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=33, start_position=-193, end_position=-1281, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=192, end_position=1280, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x356CE6"),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=3, y=-250, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356CF1"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=33, start_position=192, end_position=1280, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356CE6"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356D06"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=49, start_position=256, end_position=1280, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356C23"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=3, y=-262, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356D1B"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=33, start_position=192, end_position=1280, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356CB4"]),
	DefineObjectQueue(["command_0x356D3A", "command_0x356D79", "command_0x356DB0", "command_0x356DB0", "command_0x356DB0"], identifier="command_0x356D30"),
	RunSubroutine(["command_0x35E372"], identifier="command_0x356D3A"),
	MoveObject(speed=33, start_position=0, end_position=-1281, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357BF4"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	PlaySound(sound=S0063_GENO_BLAST_IGNITION),
	MoveObject(speed=161, start_position=0, end_position=-2049, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357BA6"]),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	PlaySound(sound=S0063_GENO_BLAST_IGNITION),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-128, y=-10, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=161, start_position=0, end_position=2048, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40, identifier="command_0x356D72"),
	Jmp(["command_0x356ACC"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x356D79"),
	MoveObject(speed=33, start_position=0, end_position=-1281, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357567"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	MoveObject(speed=129, start_position=0, end_position=2048, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357BA6"]),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-2, y=64, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=129, start_position=0, end_position=-2049, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356D72"]),
	DefineObjectQueue(["command_0x356DB6", "command_0x356DD3", "command_0x356DF0"], identifier="command_0x356DB0"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356DB6"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=65, start_position=-513, end_position=768, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=17, start_position=0, end_position=-257, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356B29"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x356DD3"),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=65, start_position=-513, end_position=768, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=17, start_position=0, end_position=256, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x356B29"]),
	RunSubroutine(["command_0x352AE5"], identifier="command_0x356DF0"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
	Jmp(["command_0x356ACC"]),
	DefineObjectQueue(["command_0x356E2D", "command_0x356E8A", "command_0x356EDF", "command_0x356F2C", "command_0x356F79", "command_0x356FB6", "command_0x356FF3", "command_0x357026", "command_0x357059", "command_0x35707A", "command_0x35709B", "command_0x3570BC", "command_0x3570DD", "command_0x3570F6", "command_0x35710F", "command_0x357123"], identifier="command_0x356E0D"),
	ResetTargetMappingMemory(identifier="command_0x356E2D"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-257, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4, identifier="command_0x356E7F"),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	Jmp(["command_0x356BCE"]),
	ResetTargetMappingMemory(identifier="command_0x356E8A"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-257, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x356ED4"),
	Jmp(["command_0x356E7F"]),
	ResetTargetMappingMemory(identifier="command_0x356EDF"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x356ED4"]),
	ResetTargetMappingMemory(identifier="command_0x356F2C"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x356ED4"]),
	ResetTargetMappingMemory(identifier="command_0x356F79"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x356ED4"]),
	ResetTargetMappingMemory(identifier="command_0x356FB6"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x356ED4"]),
	ResetTargetMappingMemory(identifier="command_0x356FF3"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C49"]),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C49"]),
	Jmp(["command_0x356ED4"]),
	ResetTargetMappingMemory(identifier="command_0x357026"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=-80, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=17, start_position=512, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C11"]),
	MoveObject(speed=17, start_position=-385, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C11"]),
	Jmp(["command_0x356ED4"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x357059"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35707A"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35709B"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x3570BC"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x3570DD"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x3570F6"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35710F"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	RunSubroutine(["command_0x352C49"]),
	Jmp(["command_0x357134"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x357123"),
	MoveObject(speed=33, start_position=-1025, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	RunSubroutine(["command_0x352C11"]),
	MoveObject(speed=17, start_position=-257, end_position=256, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x357134"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	MoveObject(speed=17, start_position=256, end_position=-385, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40),
	MoveObject(speed=17, start_position=-385, end_position=384, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=48),
	MoveObject(speed=17, start_position=384, end_position=-513, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=56),
	Jmp(["command_0x356BCE"]),
	DefineObjectQueue(["command_0x357169"], identifier="command_0x357167"),
	RunSubroutine(["command_0x35259A"], identifier="command_0x357169"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-769, end_position=0, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=33, start_position=0, end_position=992, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	ResetObjectMappingMemory(),
	PlaySound(sound=S0038_FRYING_PAN_HIT_2),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-513, end_position=512, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	Jmp(["command_0x356BCE"]),
	DefineObjectQueue(["command_0x3571BC"], identifier="command_0x3571BA"),
	DefineObjectQueue(["command_0x3571CC", "command_0x357215", "command_0x357256", "command_0x357297", "command_0x3572D8", "command_0x357309", "command_0x35733A", "command_0x357361"], identifier="command_0x3571BC"),
	ResetTargetMappingMemory(identifier="command_0x3571CC"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-769, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35720A"),
	Jmp(["command_0x356E7F"]),
	ResetTargetMappingMemory(identifier="command_0x357215"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x357256"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-97, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x357297"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=1, start_position=96, end_position=0, apply_to_y=True, should_set_speed=True),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x3572D8"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x357309"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x35733A"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352C49"]),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C49"]),
	Jmp(["command_0x35720A"]),
	ResetTargetMappingMemory(identifier="command_0x357361"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	RunSubroutine(["command_0x352C11"]),
	MoveObject(speed=33, start_position=-1025, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352C11"]),
	Jmp(["command_0x35720A"]),
	DefineObjectQueue(["command_0x357390", "command_0x3573B6", "command_0x3573D1", "command_0x3573E9"], identifier="command_0x357388"),
	ResetTargetMappingMemory(identifier="command_0x357390"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-257, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C11"]),
	MoveObject(speed=17, start_position=-513, end_position=-2049, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x3573A8"),
	RunSubroutine(["command_0x357BA6"]),
	Jmp(["command_0x356BCE"]),
	ResetTargetMappingMemory(identifier="command_0x3573B6"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-257, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C49"], identifier="command_0x3573CB"),
	Jmp(["command_0x3573A8"]),
	ResetTargetMappingMemory(identifier="command_0x3573D1"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=256, end_position=0, apply_to_x=True, should_set_speed=True),
	Jmp(["command_0x3573CB"]),
	ResetTargetMappingMemory(identifier="command_0x3573E9"),
	SetAMEM60ToCurrentTarget(),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=1, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=256, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C11"]),
	Jmp(["command_0x3573A8"]),
	DefineObjectQueue(["command_0x35740A", "command_0x357451", "command_0x357496"], identifier="command_0x357404"),
	ResetTargetMappingMemory(identifier="command_0x35740A"),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-240, z=16, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-1025, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C67"]),
	RunSubroutine(["command_0x35812B"]),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=65, start_position=-1025, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=0, apply_to_x=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-1025, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x357446"),
	Jmp(["command_0x356E7F"]),
	ResetTargetMappingMemory(identifier="command_0x357451"),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-2, y=-244, z=16, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-1025, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C67"]),
	RunSubroutine(["command_0x35812B"]),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C25"]),
	MoveObject(speed=65, start_position=-1025, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C25"]),
	Jmp(["command_0x357446"]),
	ResetTargetMappingMemory(identifier="command_0x357496"),
	ResetObjectMappingMemory(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=-248, z=16, set_x=True, set_y=True, set_z=True),
	UnknownCommand(bytearray([0x83, 0x83])),
	MoveObject(speed=1, start_position=-1025, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C67"]),
	RunSubroutine(["command_0x35812B"]),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C1B"]),
	MoveObject(speed=65, start_position=-1025, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=512, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C1B"]),
	Jmp(["command_0x357446"]),
	ReturnSubroutine(identifier="command_0x3574DB"),
	ReturnSubroutine(identifier="command_0x3574DC"),
	ResetTargetMappingMemory(identifier="command_0x3574DD"),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x60])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
	Jmp(["command_0x352163"]),
	ResetTargetMappingMemory(identifier="command_0x3574EA"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	RunSubroutine(["command_0x352163"]),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x3574FE"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=-16, y=8, z=0, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=256, arch_height=64),
	RunSubroutine(["command_0x357A3E"]),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	PlaySound(sound=S0149_ENEMY_JUMPS_HIGH),
	UnknownCommand(bytearray([0x5A])),
	MoveObject(speed=1, start_position=-513, end_position=-513, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-4097, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	UnknownCommand(bytearray([0x12, 0x81])),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=48, y=-24, z=0, set_y=True, set_z=True),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=32, y=-16, z=0, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=256, arch_height=0),
	MoveObject(speed=257, start_position=4096, end_position=8192, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	UnknownCommand(bytearray([0x59])),
	RunSubroutine(["command_0x352FC2"]),
	ResetTargetMappingMemory(identifier="command_0x35755D"),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_z=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10, identifier="command_0x357567"),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x35756D"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=80),
	RunSubroutine(["command_0x357A67"], identifier="command_0x35757C"),
	ResetObjectMappingMemory(),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357582"),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x60])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=64, identifier="command_0x357586"),
	Jmp(["command_0x352163"]),
	ResetTargetMappingMemory(identifier="command_0x35758F"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1536, arch_height=80),
	Jmp(["command_0x35757C"])
])
