# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=4001, expected_beginning=0x35DD01, script=[
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=120, y=132, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DD01"),
	NewSpriteAtCoords(sprite_id=SPR0433_MUKUMUKU, sequence=8, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=36),
	PlaySound(sound=S0206_MONSTER_SWING),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0206_MONSTER_SWING),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=28),
	PlaySound(sound=S0206_MONSTER_SWING),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0206_MONSTER_SWING),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0206_MONSTER_SWING),
	RunSubroutine(["command_0x357BA6"]),
	PlaySound(sound=S0206_MONSTER_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=3),
	RunSubroutine(["command_0x357D34"]),
	PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	SpriteSequence(sequence=10),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=10),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=3),
	RunSubroutine(["command_0x357D34"]),
	PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	SpriteSequence(sequence=10),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x35812B"]),
	SpriteSequence(sequence=4),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=65),
	ClearAMEM16Bit(0x60),
	ClearAMEM16Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35DABE"]),
	PlaySound(sound=S0112_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=12),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x35DABE"]),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=12),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	DisplayMessage(ITEM_NAME, 42),
	SpriteSequence(sequence=13),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35DABE"]),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	SpriteSequence(sequence=6),
	Jmp(["command_0x35B619"]),
	ClearAMEM8Bit(0x6C, identifier="command_0x35DDA6"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=16, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD, sequence=0, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x35DDB9"),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-20, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-24, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=-20, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-16, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	SpriteSequence(sequence=1, looping_on=True),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-8, y=-12, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-12, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0005_BIRDIE_TWEET),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=16, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	IncAMEM8Bit(0x6C),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35DDB9"]),
	Jmp(["command_0x35932E"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-3, y=-16, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DE68"),
	NewSpriteAtCoords(sprite_id=SPR0785_SPRITZ_BOMB, sequence=1, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	MoveObject(speed=65, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0517_BOMB_EXPLOSION, sequence=0, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0012_BOMB_EXPLOSION),
	Jmp(["command_0x35DA89"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DE92"),
	NewSpriteAtCoords(sprite_id=SPR0528_VERY_SMALL_BLACK_DOT, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ShineEffect(colour_count=6, starting_colour_index=1, glow_duration=1, east=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35DABE"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35DABE"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35DABE"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35DABE"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	RemoveObject(),
	UnknownCommand(bytearray([0x81])),
	Jmp(["command_0x352524"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-262, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DEFC"),
	UnknownCommand(bytearray([0x83, 0xC3])),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-244, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=96, end_position=96, apply_to_y=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35DF0F"),
	RunSubroutine(["command_0x352163"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-262, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DF1C"),
	UnknownCommand(bytearray([0x83, 0xC3])),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=54),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-244, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=96, end_position=96, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357EE2"]),
	Jmp(["command_0x35B406"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-9, y=-263, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DF41"),
	UnknownCommand(bytearray([0x83, 0xC3])),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-9, y=-245, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35DF0F"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-9, y=-263, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DF57"),
	UnknownCommand(bytearray([0x83, 0xC3])),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=54),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-9, y=-245, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=96, end_position=96, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357EE2"]),
	Jmp(["command_0x35B37C"]),
	DefineObjectQueue(["command_0x35DF7E"], identifier="command_0x35DF7C"),
	DefineObjectQueue(["command_0x35DF82", "command_0x35DFCC"], identifier="command_0x35DF7E"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-34, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DF82"),
	NewSpriteAtCoords(sprite_id=SPR0195_FLOWER, sequence=5, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	MoveObject(speed=25, start_position=-545, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PlaySound(sound=S0061_ITEM_USE),
	UnknownCommand(bytearray([0x12, 0x81])),
	ResetObjectMappingMemory(),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6E),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35DF7C"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	SetAMEMToRandomByte(amem=0x6E, upper_bound=5),
	JmpIfAMEM8BitEqualsConst(0x6E, 0, ["command_0x35DFC6"]),
	AddCoins(1),
	Jmp(["command_0x35DFC9"]),
	AddCoins(5, identifier="command_0x35DFC6"),
	Jmp(["command_0x352524"], identifier="command_0x35DFC9"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DFCC"),
	MoveObject(speed=11, start_position=-385, end_position=0, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	NewSpriteAtCoords(sprite_id=SPR0193_SMALL_COIN, sequence=2, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0013_COIN),
	PauseScriptUntilSpriteSequenceDone(),
	Jmp(["command_0x35B37C"]),
	DefineObjectQueue(["command_0x35DFED"], identifier="command_0x35DFEB"),
	DefineObjectQueue(["command_0x35DFEF"], identifier="command_0x35DFED"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35DFEF"),
	NewEffectObject(effect=EF0005_METEOR_BLAST, looping_on=True),
	UnknownCommand(bytearray([0x8A, 0x02])),
	Layer3On(property=OVERLAP_ALL, bpp4=True),
	MoveObject(speed=33, start_position=512, end_position=1024, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=17, start_position=-257, end_position=-513, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PlaySound(sound=S0105_ROCK_CANDY),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
	ResetObjectMappingMemory(),
	Jmp(["command_0x35DAA3"]),
	DefineObjectQueue(["command_0x35E01A"], identifier="command_0x35E018"),
	DefineObjectQueue(["command_0x35E032", "command_0x35E0BF", "command_0x35E0F4", "command_0x35E161", "command_0x35E188", "command_0x35E1AE", "command_0x35E1D4", "command_0x35E1FA", "command_0x35E220", "command_0x35E246", "command_0x35E26C", "command_0x35E294"], identifier="command_0x35E01A"),
	ClearAMEM16Bit(0x60, identifier="command_0x35E032"),
	ClearAMEM8Bit(0x6C),
	ClearAMEM8Bit(0x6D),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E018"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E018"]),
	PauseScriptUntilAMEMBitsSet(0x6D, [0]),
	ClearAMEM16Bit(0x62),
	ResetTargetMappingMemory(identifier="command_0x35E049"),
	MuteTimingJmp(["command_0x35E06F"]),
	ClearAMEM8Bit(0x6C),
	UseSpriteQueue(field_object=0, destinations=["command_0x35D8DE"], current_target=True),
	PauseScriptUntilAMEMBitsSet(0x6C, [0, 1, 2, 3, 4, 5, 6, 7]),
	JmpIfAMEM8BitEqualsConst(0x6C, 2, ["command_0x35E067"]),
	ClearAMEM8Bit(0x6C),
	UseSpriteQueue(field_object=0, destinations=["command_0x35E079"], current_target=True),
	PauseScriptUntilAMEMBitsSet(0x6C, [0]),
	IncAMEM16Bit(0x62, identifier="command_0x35E067"),
	JmpIfAMEM16BitLessThanConst(0x62, 6, ["command_0x35E049"]),
	SetAMEM8BitToConst(0x6D, 2, identifier="command_0x35E06F"),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	Jmp(["command_0x359D1B"]),
	ResetObjectMappingMemory(identifier="command_0x35E079"),
	ClearAMEM8Bit(0x6F),
	SetAMEMToAMEM8Bit(dest_amem=0x67, upper=0x40, amem=0x6F),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=-9, z=0, set_y=True),
	PlaySound(sound=S0115_TRANSFORM, channel=4),
	NewSpriteAtCoords(sprite_id=SPR0195_FLOWER, sequence=6, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=-1, z=0, set_y=True),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=5, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ResetTargetMappingMemory(),
	SpriteSequence(sequence=3, looping_on=True),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
	MoveObject(speed=49, start_position=0, end_position=-769, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35231D"], identifier="command_0x35E0B7"),
	RemoveObject(),
	UnknownCommand(bytearray([0xD6])),
	Jmp(["command_0x35A9E6"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=120, y=120, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E0BF"),
	NewSpriteAtCoords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=3, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=3, identifier="command_0x35E0D1"),
	SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
	PauseScriptUntilSpriteSequenceDone(),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35E0D1"]),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=120, y=112, z=0, set_x=True, set_y=True, set_z=True),
	PlaySound(sound=S0115_TRANSFORM),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0195_FLOWER, sequence=6, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x35B619"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35E0F4"),
	ClearAMEM8Bit(0x6C),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=120, y=376, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=4, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=18, destinations=["command_0x35E018"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=20, destinations=["command_0x35E018"]),
	Pause1Frame(identifier="command_0x35E130"),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 8, ["command_0x35E130"]),
	ClearAMEM8Bit(0x6C),
	ClearAMEM8Bit(0x6D),
	PlaySound(sound=S0184_SHEEP_ATTACK_2_MULTI),
	Pause1Frame(identifier="command_0x35E13D"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=22, destinations=["command_0x35E018"]),
	IncAMEM8Bit(0x6D),
	JmpIfAMEM8BitNotEqualsConst(0x6D, 16, ["command_0x35E13D"]),
	SetAMEM8BitToConst(0x6D, 1),
	RunSubroutine(["command_0x35857F"]),
	Pause1Frame(identifier="command_0x35E151"),
	SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 16, ["command_0x35E151"]),
	PlaySound(sound=S0000_SILENCE),
	Jmp(["command_0x352519"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E161"),
	RunSubroutine(["command_0x35E38D"], identifier="command_0x35E164"),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E164"]),
	RunSubroutine(["command_0x35E37B"], identifier="command_0x35E184"),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E188"),
	RunSubroutine(["command_0x35E446"], identifier="command_0x35E18B"),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E18B"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E1AE"),
	RunSubroutine(["command_0x35E4AA"], identifier="command_0x35E1B1"),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E1B1"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E1D4"),
	RunSubroutine(["command_0x35E3F2"], identifier="command_0x35E1D7"),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E1D7"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E1FA"),
	RunSubroutine(["command_0x35E4D0"], identifier="command_0x35E1FD"),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E1FD"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E220"),
	RunSubroutine(["command_0x35E3BC"], identifier="command_0x35E223"),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E223"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E246"),
	RunSubroutine(["command_0x35E474"], identifier="command_0x35E249"),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	RunSubroutine(["command_0x35E418"]),
	RunSubroutine(["command_0x35E446"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E249"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E370"], identifier="command_0x35E26C"),
	PlaySound(sound=S0182_SHEEP_ATTACK_1),
	RunSubroutine(["command_0x35E418"], identifier="command_0x35E271"),
	RunSubroutine(["command_0x35E446"]),
	RunSubroutine(["command_0x35E474"]),
	RunSubroutine(["command_0x35E4AA"]),
	RunSubroutine(["command_0x35E4D0"]),
	RunSubroutine(["command_0x35E38D"]),
	RunSubroutine(["command_0x35E3BC"]),
	RunSubroutine(["command_0x35E3F2"]),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 1, ["command_0x35E271"]),
	Jmp(["command_0x35E184"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35E294"),
	ClearAMEM8Bit(0x6C),
	SetAMEMToRandomByte(amem=0x6E, upper_bound=10),
	SetAMEM8BitToAMEM(amem=0x6D, source_amem=0x6E, upper=0x60),
	ResetTargetMappingMemory(identifier="command_0x35E2A0"),
	JmpIfAMEM8BitEqualsConst(0x6E, 0, ["command_0x35E2DD"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35E2E8"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35E2F3"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35E2FE"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35E309"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 5, ["command_0x35E314"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 6, ["command_0x35E31F"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 7, ["command_0x35E32A"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 8, ["command_0x35E335"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 9, ["command_0x35E340"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=64, y=24, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E2DD"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=128, y=24, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E2E8"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=192, y=24, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E2F3"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=64, y=216, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E2FE"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=128, y=216, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E309"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=192, y=216, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E314"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=8, y=74, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E31F"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=8, y=148, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E32A"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=240, y=74, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E335"),
	Jmp(["command_0x35E34B"]),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=240, y=148, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E340"),
	Jmp(["command_0x35E34B"]),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2048, arch_height=0, identifier="command_0x35E34B"),
	IncAMEM8Bit(0x6C),
	SetAMEMToRandomByte(amem=0x6E, upper_bound=10, identifier="command_0x35E353"),
	JmpIfAMEM8BitEqualsAMEM(amem=0x6E, source_amem=0x6D, upper=0x60, destinations=["command_0x35E353"]),
	SetAMEM8BitToAMEM(amem=0x6D, source_amem=0x6E, upper=0x60),
	RunSubroutine(["command_0x357EE2"]),
	SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6D),
	JmpIfAMEM8BitNotEqualsConst(0x6A, 2, ["command_0x35E2A0"]),
	Jmp(["command_0x359227"]),
	ClearAMEM8Bit(0x6E, identifier="command_0x35E370"),
	RunSubroutine(["command_0x352640"], identifier="command_0x35E372"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ReturnSubroutine(),
	Jmp(["command_0x358091"], identifier="command_0x35E378"),
	ResetTargetMappingMemory(identifier="command_0x35E37B"),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-256, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
	Jmp(["command_0x35B4E9"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-272, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E38D"),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-266, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=208, end_position=208, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=120, end_position=120, apply_to_y=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35E3B0"),
	RunSubroutine(["command_0x35E378"], identifier="command_0x35E3B8"),
	ReturnSubroutine(),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-266, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E3BC"),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=16, y=-256, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=120, end_position=120, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=208, end_position=208, apply_to_y=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35E3E7"),
	Jmp(["command_0x35E3B8"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=16, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E3F2"),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-246, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=-121, end_position=-121, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x35E3E7"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-246, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E418"),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-240, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=-209, end_position=-209, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x35E3B0"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-240, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E446"),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-10, y=-246, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=-209, end_position=-209, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-121, end_position=-121, apply_to_y=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35E469"),
	Jmp(["command_0x35E3B8"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-10, y=-246, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E474"),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-16, y=-256, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=-121, end_position=-121, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-209, end_position=-209, apply_to_y=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35E49F"),
	Jmp(["command_0x35E3B8"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-16, y=-256, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E4AA"),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-10, y=-266, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=120, end_position=120, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x35E49F"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-10, y=-266, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E4D0"),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35E378"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-272, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=208, end_position=208, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x35E469"]),
	DefineObjectQueue(["command_0x35E500"], identifier="command_0x35E4FE"),
	DefineObjectQueue(["command_0x35E506", "command_0x35E542", "command_0x35E5D9"], identifier="command_0x35E500"),
	ClearAMEM16Bit(0x60, identifier="command_0x35E506"),
	ClearAMEM8Bit(0x6C),
	ClearAMEM8Bit(0x6D),
	ClearAMEM8Bit(0x6E),
	SetAMEM8BitToUnknownShort(amem=0x6A, type=0x8, value=0x0001),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E4FE"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E4FE"]),
	PauseScriptUntilAMEMBitsSet(0x6D, [0]),
	ClearAMEM16Bit(0x62),
	ResetTargetMappingMemory(),
	MuteTimingJmp(["command_0x35E53B"]),
	UseSpriteQueue(field_object=0, destinations=["command_0x35D8DE"], current_target=True),
	PauseScriptUntilAMEMBitsSet(0x6C, [0, 1, 2, 3, 4, 5, 6, 7]),
	JmpIfAMEM8BitEqualsConst(0x6C, 2, ["command_0x35E53B"]),
	ClearAMEM8Bit(0x6C),
	UseSpriteQueue(field_object=0, destinations=["command_0x35E60E"], current_target=True),
	PauseScriptUntilAMEMBitsSet(0x6C, [0]),
	SetAMEM8BitToConst(0x6D, 255, identifier="command_0x35E53B"),
	Jmp(["command_0x359D1B"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E542"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-16, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	PlaySound(sound=S0115_TRANSFORM),
	NewSpriteAtCoords(sprite_id=SPR0195_FLOWER, sequence=6, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-16, y=0, z=0, set_x=True, set_y=True, set_z=True),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=3, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM8BitToConst(0x6D, 1),
	RunSubroutine(["command_0x35857F"]),
	SpriteSequence(sequence=4, looping_on=True),
	Pause1Frame(identifier="command_0x35E572"),
	SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
	JmpIfAMEM8BitEqualsConst(0x6D, 255, ["command_0x35E5C5"]),
	JmpIfAMEM8BitNotEqualsConst(0x6D, 0, ["command_0x35E572"]),
	SpriteSequence(sequence=3, looping_on=True),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
	PlaySound(sound=S0181_LAMB_S_LURE_SINGLE),
	MoveObject(speed=49, start_position=0, end_position=-769, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=512, end_position=-513, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	DisplayMessage(ITEM_NAME, 16),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x35231D"]),
	SetAMEM8BitToAbsolute7E(0x6E, 0x7EE012),
	IncAMEM8Bit(0x6E),
	JmpIfAMEM8BitLessThanConst(0x6E, 48, ["command_0x35E5BE"]),
	RemoveItemFromStandardInventory(LambsLureItem),
	AddItemToStandardInventory(SheepAttackItem),
	DisplayMessage(ITEM_NAME, 14),
	PauseScriptUntilDialogClosed(),
	ClearAMEM8Bit(0x6E),
	SetAbsolute7EToAMEM8Bit(0x7EE012, 0x6E, identifier="command_0x35E5BE"),
	Jmp(["command_0x35E5D6"]),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-16, y=-8, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E5C5"),
	PlaySound(sound=S0115_TRANSFORM),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0195_FLOWER, sequence=6, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Jmp(["command_0x35A88E"], identifier="command_0x35E5D6"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=87, identifier="command_0x35E5D9"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-16, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0793_BIG_PINK_HEART, sequence=2, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=0, z=0, set_z=True),
	MoveObject(speed=17, start_position=-305, end_position=304, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=136, end_position=136, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
	RunSubroutine(["command_0x3522C9"]),
	RemoveObject(),
	ReturnObjectQueue(),
	ResetObjectMappingMemory(identifier="command_0x35E60E"),
	ClearAMEM8Bit(0x6F),
	SetAMEMToAMEM8Bit(dest_amem=0x67, upper=0x40, amem=0x6F),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=-9, z=0, set_y=True),
	PlaySound(sound=S0115_TRANSFORM),
	NewSpriteAtCoords(sprite_id=SPR0195_FLOWER, sequence=6, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=-1, z=0, set_y=True),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=5, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ResetTargetMappingMemory(),
	SpriteSequence(sequence=3, looping_on=True),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
	MoveObject(speed=49, start_position=0, end_position=-769, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=-513, end_position=512, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	ClearAMEM8Bit(0x6D),
	RunSubroutine(["command_0x35857F"]),
	Jmp(["command_0x35E0B7"]),
	DefineObjectQueue(["command_0x35E65E"], identifier="command_0x35E65C"),
	DefineObjectQueue(["command_0x35E670", "command_0x35E6D4", "command_0x35E6E1", "command_0x35E6ED", "command_0x35E6F9", "command_0x35E705", "command_0x35E711", "command_0x35E71D", "command_0x35E729"], identifier="command_0x35E65E"),
	ClearAMEM16Bit(0x60, identifier="command_0x35E670"),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=256, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0274_THE_BIG_BOO, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, mirror_sprite=True, overlap_all_sprites=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35E65C"]),
	Pause1Frame(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35E65C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=16, destinations=["command_0x35E65C"]),
	PlaySound(sound=S0175_DEATHSICKLE),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM8BitToConst(0x6F, 1),
	Pause1Frame(identifier="command_0x35E6AF"),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 8, ["command_0x35E6AF"]),
	SetAMEM60ToCurrentTarget(),
	SetAMEM8BitToUnknownShort(amem=0x6E, type=0xB, value=0x0043),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x35E6D0"]),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-24, z=0, set_x=True, set_y=True, set_z=True),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0571_FEAR_EXCLAMATION_POINT, sequence=0, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(identifier="command_0x35E6D0"),
	Jmp(["command_0x352528"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E6D4"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=24, y=-40, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x35E735"], identifier="command_0x35E6DD"),
	ReturnObjectQueue(),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E6E1"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=24, y=8, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E6ED"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-24, y=-40, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E6F9"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-24, y=8, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E705"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-44, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E711"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=12, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E71D"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-28, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E729"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=28, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35E6DD"]),
	UnknownCommand(bytearray([0x83, 0x83]), identifier="command_0x35E735"),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=320, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	Pause1Frame(identifier="command_0x35E748"),
	SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35E748"]),
	RemoveObject(identifier="command_0x35E753"),
	Jmp(["command_0x35B4CE"]),
	DefineObjectQueue(["command_0x35E759"], identifier="command_0x35E757"),
	DefineObjectQueue(["command_0x35E75D", "command_0x35E7FD"], identifier="command_0x35E759"),
	ClearAMEM8Bit(0x6F, identifier="command_0x35E75D"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-34, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0462_EGGBERT, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	MoveObject(speed=25, start_position=-545, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PlaySound(sound=S0061_ITEM_USE),
	RunSubroutine(["command_0x35E857"]),
	UnknownCommand(bytearray([0x12, 0x81])),
	ResetObjectMappingMemory(),
	JmpIfAMEM8BitEqualsConst(0x6F, 2, ["command_0x35E7CA"]),
	MoveObject(speed=33, start_position=0, end_position=512, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=17),
	ResetObjectMappingMemory(),
	ClearAMEM16Bit(0x60),
	JmpIfAMEM8BitEqualsConst(0x6F, 1, ["command_0x35E7B9"]),
	SetAMEM8BitToConst(0x6D, 1),
	ClearAMEM8Bit(0x6E),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E757"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	RemoveObject(),
	PlaySound(sound=S0007_ERROR_INCORRECT_ANSWER),
	NewSpriteAtCoords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True, identifier="command_0x35E7AB"),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	Jmp(["command_0x35E7FA"]),
	ClearAMEM8Bit(0x6D, identifier="command_0x35E7B9"),
	ClearAMEM8Bit(0x6E),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E757"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	RemoveObject(),
	PlaySound(sound=S0064_EGG_HATCH),
	Jmp(["command_0x35E7AB"]),
	RemoveObject(identifier="command_0x35E7CA"),
	PlaySound(sound=S0115_TRANSFORM),
	NewSpriteAtCoords(sprite_id=SPR0195_FLOWER, sequence=6, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM, sequence=5, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	DisplayMessage(ITEM_NAME, 15),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
	PlaySound(sound=S0181_LAMB_S_LURE_SINGLE),
	SpriteSequence(sequence=3, looping_on=True),
	MoveObject(speed=49, start_position=0, end_position=-769, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x35231D"]),
	RemoveObject(),
	Jmp(["command_0x352524"], identifier="command_0x35E7FA"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=1, y=-26, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E7FD"),
	PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
	NewSpriteAtCoords(sprite_id=SPR0793_BIG_PINK_HEART, sequence=2, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True),
	MoveObject(speed=97, start_position=-513, end_position=512, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
	JmpIfAMEM8BitEqualsConst(0x6D, 1, ["command_0x35E851"]),
	ClearAMEM8Bit(0x6C),
	MoveObject(speed=1, start_position=240, end_position=240, apply_to_x=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x35E829"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	MoveObject(speed=1, start_position=-241, end_position=-241, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	IncAMEM8Bit(0x6C),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 6, ["command_0x35E829"]),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	Jmp(["command_0x35E854"]),
	SpriteSequence(sequence=4, identifier="command_0x35E851"),
	PauseScriptUntilSpriteSequenceDone(),
	Jmp(["command_0x35A88E"], identifier="command_0x35E854"),
	SetAMEM8BitToUnknownShort(amem=0x6A, type=0x8, value=0x0001, identifier="command_0x35E857"),
	SetAMEM8BitToAbsolute7E(0x6B, 0x7EE012),
	JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35E871"]),
	Pause1Frame(),
	JmpIfAMEM8BitLessThanConst(0x6B, 1, ["command_0x35E899"]),
	DecAMEM8Bit(0x6B),
	Jmp(["command_0x35E895"]),
	SetAMEM8BitToUnknownShort(amem=0x6A, type=0x8, value=0x001E, identifier="command_0x35E871"),
	JmpIfAMEM8BitNotEqualsConst(0x6A, 83, ["command_0x35E899"]),
	Pause1Frame(),
	SetAMEM8BitToConst(0x6F, 1),
	IncAMEM8Bit(0x6B),
	JmpIfAMEM8BitLessThanConst(0x6B, 10, ["command_0x35E895"]),
	Pause1Frame(),
	SetAMEM8BitToConst(0x6F, 2),
	RemoveItemFromStandardInventory(MysteryEggItem),
	AddItemToStandardInventory(LambsLureItem),
	ClearAMEM8Bit(0x6B),
	SetAbsolute7EToAMEM8Bit(0x7EE012, 0x6B, identifier="command_0x35E895"),
	ReturnSubroutine(identifier="command_0x35E899"),
	DefineObjectQueue(["command_0x35E89C"], identifier="command_0x35E89A"),
	DefineObjectQueue(["command_0x35E89E"], identifier="command_0x35E89C"),
	SetAMEM60ToCurrentTarget(identifier="command_0x35E89E"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=-38, z=0, set_x=True, set_y=True, set_z=True),
	InitializeBonusMessageSequence(),
	PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
	DisplayBonusMessage(message=BM_LUCKY, x=0, y=6),
	PauseScriptUntilBonusMessageComplete(),
	SetAMEM8BitToAbsolute7E(0x6F, 0x7EFA1F),
	SetAMEMBits(0x6F, [0]),
	SetAbsolute7EToAMEM8Bit(0x7EFA1F, 0x6F),
	Pause1Frame(),
	SetAMEM8BitToAbsolute7E(0x6F, 0x7EE014),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35E8CA"]),
	SetAMEM8BitToConst(0x6F, 11),
	DecAMEM8Bit(0x6F, identifier="command_0x35E8CA"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35E8D5"]),
	RemoveItemFromStandardInventory(LuckyJewelItem),
	SetAbsolute7EToAMEM8Bit(0x7EE014, 0x6F, identifier="command_0x35E8D5"),
	Pause1Frame(),
	Jmp(["command_0x352524"]),
	DefineObjectQueue(["command_0x35E8DF"], identifier="command_0x35E8DD"),
	DefineObjectQueue(["command_0x35E8E7", "command_0x35E962", "command_0x35E977", "command_0x35E98B"], identifier="command_0x35E8DF"),
	ClearAMEM16Bit(0x60, identifier="command_0x35E8E7"),
	SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6E),
	ClearAMEM8Bit(0x6E),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=48, y=154, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E8DD"]),
	RunSubroutine(["command_0x35812B"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=64, y=162, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E8DD"]),
	RunSubroutine(["command_0x35812B"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=80, y=170, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35E8DD"]),
	RunSubroutine(["command_0x35812B"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=96, y=178, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E8DD"]),
	RunSubroutine(["command_0x35812B"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=112, y=186, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E8DD"]),
	RunSubroutine(["command_0x35812B"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=128, y=194, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35E8DD"]),
	Pause1Frame(identifier="command_0x35E946"),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 6, ["command_0x35E946"]),
	JmpIfAMEM8BitEqualsConst(0x6D, 1, ["command_0x35E959"]),
	DisplayMessage(ITEM_NAME, 44),
	Jmp(["command_0x35E95C"]),
	DisplayMessage(ITEM_NAME, 45, identifier="command_0x35E959"),
	PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP, identifier="command_0x35E95C"),
	PauseScriptUntilDialogClosed(),
	Jmp(["command_0x352524"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E962"),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35E99F"], identifier="command_0x35E973"),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E977"),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x35E973"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35E98B"),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6600, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x35E973"]),
	SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6D, identifier="command_0x35E99F"),
	JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35E9AE"]),
	PlaySound(sound=S0076_STAT_BOOST_SINGLE),
	Jmp(["command_0x35E9B0"]),
	PlaySound(sound=S0077_STAT_BOOST_MULTI, identifier="command_0x35E9AE"),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35E9B0"),
	Jmp(["command_0x35E753"]),
	DefineObjectQueue(["command_0x35E9B6"], identifier="command_0x35E9B4"),
	DefineObjectQueue(["command_0x35E9C2", "command_0x35EAAB", "command_0x35EAEA", "command_0x35EB23", "command_0x35EA44", "command_0x35EA94"], identifier="command_0x35E9B6"),
	ClearAMEM16Bit(0x60, identifier="command_0x35E9C2"),
	ClearAMEM16Bit(0x6C),
	ClearAMEM16Bit(0x6E),
	SetAMEM8BitToUnknownShort(amem=0x6A, type=0x8, value=0x0001),
	PlaySound(sound=S0071_PSYCHOPATH_DRUM_ROLL),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35E9B4"]),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=128, y=140, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0432_STARSLAP, sequence=3, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35E9B4"]),
	PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35E9B4"]),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35EA03"]),
	SpriteSequence(sequence=10),
	Jmp(["command_0x35EA08"]),
	SpriteSequence(sequence=13, identifier="command_0x35EA03"),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35EA08"),
	RunSubroutine(["command_0x35812B"]),
	SpriteSequence(sequence=4, looping_off=True),
	MoveObject(speed=97, start_position=-1025, end_position=1024, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=45),
	PauseScriptUntilAMEMBitsSet(0x6C, [0]),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35E9B4"]),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0518_SMALL_WHITE_CLOUD, sequence=0, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0115_TRANSFORM),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM8BitToConst(0x6E, 1),
	RemoveObject(),
	PauseScriptUntilAMEMBitsSet(0x6D, [0]),
	Jmp(["command_0x352528"]),
	SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A, identifier="command_0x35EA44"),
	UnknownCommand(bytearray([0xA6])),
	ClearAMEM8Bit(0x6C),
	ClearAMEM16Bit(0x60),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=160, y=156, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0434_ZEOSTAR, sequence=4, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35E9B4"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=94),
	SpriteSequence(sequence=11),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=11),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=10),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35EA7E"]),
	SpriteSequence(sequence=10),
	Jmp(["command_0x35EA83"]),
	SpriteSequence(sequence=13, identifier="command_0x35EA7E"),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=13),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35EA83"),
	RunSubroutine(["command_0x358126"]),
	SpriteSequence(sequence=12),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM8BitToConst(0x6C, 1),
	RemoveObject(),
	Pause1Frame(),
	UnknownCommand(bytearray([0xA5])),
	Jmp(["command_0x35922E"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=96, y=124, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35EA94"),
	UnknownCommand(bytearray([0x83, 0x83])),
	Pause1Frame(identifier="command_0x35EA9E"),
	SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35EA9E"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=32, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35EAAB"),
	DoMaskEffect(CIRCLE_MASK),
	SetMaskCoords(points=[], extra_byte=0x10),
	UnknownCommand(bytearray([0x8B, 0x11, 0x01, 0x02, 0x01])),
	ScreenFlash(NO_COLOUR, 8),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=128, y=131, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=352, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	SetMaskCoords(points=[], extra_byte=0x18),
	RunSubroutine(["command_0x35884B"]),
	Pause1Frame(identifier="command_0x35EAD6"),
	SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35EAD6"]),
	DisableSpritesOnSubscreen(),
	UnknownCommand(bytearray([0x90])),
	UnknownCommand(bytearray([0xC4])),
	UnknownCommand(bytearray([0xC5])),
	SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6F),
	ReturnObjectQueue(),
	SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A, identifier="command_0x35EAEA"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	PlaySound(sound=S0037_MONSTER_ITEM_TOSS),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=44),
	PlaySound(sound=S0037_MONSTER_ITEM_TOSS),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=29),
	PlaySound(sound=S0010_MALLOW_PUNCH_1),
	RunSubroutine(["command_0x358130"]),
	PlaySound(sound=S0010_MALLOW_PUNCH_1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=27),
	JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35EB1A"]),
	PlaySound(sound=S0010_MALLOW_PUNCH_1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	PlaySound(sound=S0010_MALLOW_PUNCH_1),
	Jmp(["command_0x35EB22"]),
	PlaySound(sound=S0048_MALLOW_PUNCH_2, identifier="command_0x35EB1A"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	PlaySound(sound=S0048_MALLOW_PUNCH_2),
	ReturnObjectQueue(identifier="command_0x35EB22"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=80, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35EB23"),
	NewSpriteAtCoords(sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=272, y=80, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=640, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	Jmp(["command_0x352519"])
])
