# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=322, expected_beginning=0x3579A2, script=[
	ResetTargetMappingMemory(identifier="command_0x3579A2"),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x40])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=80),
	RunSubroutine(["command_0x357EE2"]),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x80])),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=2048, arch_height=0),
	RunSubroutine(["command_0x357EE2"]),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=-101, start_position=0, end_position=-513, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=103, start_position=-513, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ResetObjectMappingMemory(),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357A01"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1280, arch_height=96),
	Jmp(["command_0x35757C"]),
	ResetTargetMappingMemory(identifier="command_0x357A13"),
	ResetObjectMappingMemory(),
	MoveObject(speed=17, start_position=256, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x357D34"]),
	MoveObject(speed=25, start_position=-769, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x358035"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=32, y=-16, z=-32, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	PauseScriptUntil(condition=UNKNOWN_PAUSE_4, identifier="command_0x357A3E"),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357A43"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=-16, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	RunSubroutine(["command_0x357E96"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=128),
	PauseScriptUntil(condition=UNKNOWN_PAUSE_7, identifier="command_0x357A67"),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357A6C"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=-16, y=8, z=0, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=256, arch_height=64),
	RunSubroutine(["command_0x357A3E"]),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	UnknownCommand(bytearray([0x5A])),
	MoveObject(speed=1, start_position=-513, end_position=-513, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-4097, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	UnknownCommand(bytearray([0x12, 0x81])),
	ResetObjectMappingMemory(),
	SpriteSequence(sequence=5),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=48, y=-24, z=0, set_y=True, set_z=True),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=32, y=-16, z=0, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=256, arch_height=0),
	MoveObject(speed=257, start_position=4096, end_position=8192, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	UnknownCommand(bytearray([0x59])),
	Jmp(["command_0x35755D"])
])
