# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=872, expected_beginning=0x350202, script=[
	DefineObjectQueue([
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_1_slide_backward_when_hit"
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_10_fade_out_death_floating", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_2_bowser_clone_sprite", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_6_floating_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_4_no_reaction_when_hit", 
        "monster_sprite_behaviour_12_fade_out_death_2", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_8_floating_slide_backward_when_hit", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_3_mario_clone_sprite", 
        "monster_sprite_behaviour_1_slide_backward_when_hit", 
        "monster_sprite_behaviour_2_bowser_clone_sprite", 
        "monster_sprite_behaviour_1_slide_backward_when_hit", 
        "monster_sprite_behaviour_1_slide_backward_when_hit", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_1_slide_backward_when_hit", 
        "monster_sprite_behaviour_1_slide_backward_when_hit", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2",
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_8_floating_slide_backward_when_hit", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_17_no_reaction_when_hit_2", 
        "monster_sprite_behaviour_16_normal", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_11_fade_out_death",
        "monster_sprite_behaviour_7_floating", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_7_floating", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_12_fade_out_death_2", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_10_fade_out_death_floating", 
        "monster_sprite_behaviour_10_fade_out_death_floating", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_3_mario_clone_sprite", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_13_fade_out_death_smithy_spell_cast", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_14_fade_out_death_no_escape_movement", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_2_bowser_clone_sprite", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_11_fade_out_death", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_5_sprite_shadow", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_15_fade_out_death_no_escape_transition", 
        "monster_sprite_behaviour_0_no_movement_for_escape", 
        "monster_sprite_behaviour_9_floating_slide_backward_when_hit_2"
    ], identifier="monster_sprite_behaviour_pointers"),
	DefineObjectQueue(["command_0x350452", "command_0x350458", "command_0x350474", "command_0x350478", "command_0x350497", "command_0x3504B5", "command_0x3504D3", "command_0x3504E4"], identifier="command_0x350402"),
	DefineObjectQueue(["command_0x350452", "command_0x350458", "command_0x350474", "command_0x35047F", "command_0x35049D", "command_0x3504BB", "command_0x3504D3", "command_0x3504E4"], identifier="command_0x350412"),
	DefineObjectQueue(["command_0x350452", "command_0x350458", "command_0x350474", "command_0x350485", "command_0x3504A3", "command_0x3504C1", "command_0x3504D3", "command_0x3504E4"], identifier="command_0x350422"),
	DefineObjectQueue(["command_0x350452", "command_0x350458", "command_0x350474", "command_0x35048B", "command_0x3504A9", "command_0x3504C7", "command_0x3504D3", "command_0x3504E4"], identifier="command_0x350432"),
	DefineObjectQueue(["command_0x350452", "command_0x350458", "command_0x350474", "command_0x350491", "command_0x3504AF", "command_0x3504CD", "command_0x3504D3", "command_0x3504E4"], identifier="command_0x350442"),
	UnknownCommand(bytearray([0x16]), identifier="command_0x350452"),
	UnknownCommand(bytearray([0x14]), identifier="command_0x350453"),
	Pause1Frame(),
	Jmp(["command_0x350453"]),
	ResetTargetMappingMemory(identifier="command_0x350458"),
	ResetObjectMappingMemory(),
	UnknownCommand(bytearray([0x54])),
	UnknownCommand(bytearray([0x6C])),
	UnknownCommand(bytearray([0x3E])),
	UnknownCommand(bytearray([0x6D])),
	UnknownCommand(bytearray([0x57])),
	UnknownCommand(bytearray([0x3B])),
	UnknownCommand(bytearray([0x55])),
	Pause1Frame(),
	UnknownCommand(bytearray([0x3B])),
	UnknownCommand(bytearray([0x56])),
	JmpIfTargetEnabled(["command_0x350470"]),
	SpriteSequence(sequence=7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
	SpriteSequence(sequence=8, looping_off=True),
	Pause1Frame(),
	GameOverIfNoAlliesStanding(identifier="command_0x350470"),
	Jmp(["command_0x350453"]),
	UnknownCommand(bytearray([0x4F]), identifier="command_0x350474"),
	Jmp(["command_0x350453"]),
	RunSubroutine(["command_0x358916"], identifier="command_0x350478"),
	UnknownCommand(bytearray([0x16]), identifier="command_0x35047B"),
	Jmp(["command_0x350453"]),
	RunSubroutine(["command_0x3589D5"], identifier="command_0x35047F"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358A6C"], identifier="command_0x350485"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358B57"], identifier="command_0x35048B"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358BEC"], identifier="command_0x350491"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358991"], identifier="command_0x350497"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358A26"], identifier="command_0x35049D"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358B10"], identifier="command_0x3504A3"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358BA6"], identifier="command_0x3504A9"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358C48"], identifier="command_0x3504AF"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x35899C"], identifier="command_0x3504B5"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358A29"], identifier="command_0x3504BB"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358B13"], identifier="command_0x3504C1"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358BA9"], identifier="command_0x3504C7"),
	Jmp(["command_0x35047B"]),
	RunSubroutine(["command_0x358C4B"], identifier="command_0x3504CD"),
	Jmp(["command_0x35047B"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=36, identifier="command_0x3504D3"),
	UnknownCommand(bytearray([0x6C])),
	UnknownCommand(bytearray([0x6D])),
	PauseScriptUntilAMEMBitsSet(0x60, [0], identifier="command_0x3504D9"),
	SpriteSequence(sequence=10),
	PauseScriptUntilSpriteSequenceDone(),
	ClearAMEM8Bit(0x60),
	Jmp(["command_0x3504D9"]),
	ResetTargetMappingMemory(identifier="command_0x3504E4"),
	ResetObjectMappingMemory(),
	SetAMEM8BitToRAMRelative7E(0x60, 0x7E0040),
	JmpIfAMEMBitsSet(0x60, [1], ["command_0x350514"]),
	JmpIfAMEMBitsSet(0x60, [5, 6], ["command_0x350515"]),
	SetAMEM8BitToRAMRelative7E(0x62, 0x7E0001),
	ClearAMEM8Bit(0x63),
	SpriteQueueReferenceEXPERIMENTAL(unknown_byte=2, destinations=["command_0x35051F"]),
	SetSequenceSpeed(3),
	MoveObject(speed=1, start_position=-801, end_position=-801, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=400, end_position=400, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=64),
	ActorExitBattleEXPERIMENTAL(identifier="command_0x350514"),
	SpriteSequence(sequence=1, identifier="command_0x350515"),
	UnknownCommand(bytearray([0xA2, 0x17, 0x04, 0x06, 0x04])),
	SetAMEMToRandomByte(amem=0x65, upper_bound=2),
	DefineObjectQueue(["command_0x350529", "command_0x350530", "command_0x350537", "command_0x35053E", "command_0x350545"], identifier="command_0x35051F"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, looping=True, overlap_all_sprites=True, identifier="command_0x350529"),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0007_TOADSTOOL_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, looping=True, overlap_all_sprites=True, identifier="command_0x350530"),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0013_BOWSER_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, looping=True, overlap_all_sprites=True, identifier="command_0x350537"),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0025_GENO_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, looping=True, overlap_all_sprites=True, identifier="command_0x35053E"),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=0, store_to_vram=True, looping=True, overlap_all_sprites=True, identifier="command_0x350545"),
	ReturnSubroutine()
])
