# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=617, expected_beginning=0x357D0B, script=[
	ResetTargetMappingMemory(identifier="command_0x357D0B"),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x38])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=96),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=3),
	RunSubroutine(["command_0x35811C"]),
	SpriteSequence(sequence=6),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-24, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=192),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=5),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16, identifier="command_0x357D34"),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357D39"),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x38])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=1280, arch_height=0),
	RunSubroutine(["command_0x352163"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0189_CROCO_STILL, sequence=3, store_to_vram=True, store_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5, looping_on=True),
	PlaySound(sound=S0011_SWOOSH_RUN_AWAY),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=16, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=1280, arch_height=0),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=5, looping_off=True),
	MoveObject(speed=1, start_position=256, end_position=0, apply_to_x=True, should_set_speed=True),
	RunSubroutine(["command_0x352C11"]),
	RunSubroutine(["command_0x357567"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0496_CROCO_ST_TIME, sequence=0, store_to_vram=True, looping=True, store_palette=True, overlap_all_sprites=True),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357D7C"),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x40])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=80),
	RunSubroutine(["command_0x357EE2"]),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x70])),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5),
	PlaySound(sound=S0087_BIG_BOUNCE),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-193, end_position=-193, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=129, start_position=-1537, end_position=1536, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	PlaySound(sound=S0087_BIG_BOUNCE),
	MoveObject(speed=129, start_position=-1537, end_position=1536, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	PlaySound(sound=S0087_BIG_BOUNCE),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=64, end_position=64, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=65, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	PlaySound(sound=S0195_EXPLOSIVE_HIT),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	SpriteSequence(sequence=6, identifier="command_0x357DF3"),
	PauseScriptUntilSpriteSequenceDone(),
	VisibilityOff(unknown_byte=0x01),
	RunSubroutine(["command_0x357F0F"]),
	SpriteSequence(sequence=5, looping_off=True),
	VisibilityOn(unknown_byte=0x01),
	SpriteSequence(sequence=5),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	SpriteSequence(sequence=6, identifier="command_0x357E09"),
	PauseScriptUntilSpriteSequenceDone(),
	VisibilityOff(unknown_byte=0x01),
	RunSubroutine(["command_0x357ED3"], identifier="command_0x357E0E"),
	SpriteSequence(sequence=5, looping_off=True),
	VisibilityOn(unknown_byte=0x01),
	Jmp(["command_0x3522D3"]),
	SpriteSequence(sequence=6, identifier="command_0x357E18"),
	PauseScriptUntilSpriteSequenceDone(),
	VisibilityOff(unknown_byte=0x01),
	ResetTargetMappingMemory(),
	ResetObjectMappingMemory(),
	RunSubroutine(["command_0x352729"]),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=7, looping_off=True),
	VisibilityOn(unknown_byte=0x01),
	PlaySound(sound=S0206_MONSTER_SWING),
	SpriteSequence(sequence=7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
	PlaySound(sound=S0206_MONSTER_SWING),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	PlaySound(sound=S0206_MONSTER_SWING),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	PlaySound(sound=S0206_MONSTER_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	VisibilityOff(unknown_byte=0x01),
	SetOMEM60To072C(),
	DisplayMessageAtOMEM60As(ATTACK_NAME),
	Jmp(["command_0x357E0E"]),
	SpriteSequence(sequence=6, identifier="command_0x357E4E"),
	PauseScriptUntilSpriteSequenceDone(),
	VisibilityOff(unknown_byte=0x01),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	UnknownCommand(bytearray([0x44, 0x38])),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=64),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=5, looping_off=True),
	VisibilityOn(unknown_byte=0x01),
	SpriteSequence(sequence=5),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0502_BOOSTER, sequence=0, store_to_vram=True, store_palette=True, overlap_all_sprites=True, bit_4=True, identifier="command_0x357E68"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=8, y=8, z=-16, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=512, arch_height=0),
	RunSubroutine(["command_0x352163"]),
	SpriteSequence(sequence=2, looping_off=True),
	RunSubroutine(["command_0x35337D"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=32, y=-16, z=-8, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
	RunSubroutine(["command_0x357EE2"], identifier="command_0x357E96"),
	ResetSpriteSequence(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357E9B"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-8, y=4, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	Jmp(["command_0x3578FB"]),
	ResetTargetMappingMemory(identifier="command_0x357EAE"),
	MoveObject(speed=65, start_position=-769, end_position=-1537, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=33, start_position=384, end_position=768, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=14),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x357EC5"),
	ResetTargetMappingMemory(identifier="command_0x357EC6"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=96, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x357586"]),
	ResetTargetMappingMemory(identifier="command_0x357ED3"),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x357EE2"),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x357EE7"),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=512, arch_height=0),
	Jmp(["command_0x357EE2"]),
	ResetTargetMappingMemory(identifier="command_0x357EFB"),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1024, arch_height=0),
	Jmp(["command_0x357EE2"]),
	ResetTargetMappingMemory(identifier="command_0x357F0F"),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=-16, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
	Jmp(["command_0x357EE2"])
])
