# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=4958, expected_beginning=0x35ECA2, script=[
	DefineObjectQueue([
        "command_0x35ECEA", 
        "command_0x35ED03", 
        "command_0x35ED21", 
        "command_0x35ED42", 
        "command_0x35ED56", 
        "command_0x35ED6F", 
        "command_0x35ED92", 
        "command_0x35EDB5", 
        "command_0x35EDC9", 
        "command_0x35EDE0", 
        "command_0x35EDF4", 
        "command_0x35EE18", 
        "command_0x35EE34", 
        "command_0x35EE42", 
        "command_0x35EE54", 
        "command_0x35EE77", 
        "command_0x35EE8B", 
        "command_0x35EE9F", 
        "command_0x35EEB6", 
        "command_0x35EEC6", 
        "command_0x35EEE9", 
        "command_0x35EF0C", 
        "command_0x35EF20", 
        "command_0x35EF41", 
        "command_0x35EF59", 
        "command_0x35EF73", 
        "command_0x35EF99", 
        "command_0x35EFAD", 
        "command_0x35EFC6", 
        "command_0x35EFE7", 
        "command_0x35F007", 
        "command_0x35F02B", 
        "command_0x35F03F", 
        "command_0x35F051", 
        "command_0x35F061", 
        "command_0x35F084",
        "stella023_weapon",
        "sagestick_weapon",
        "wonderchomp_weapon",
    ], identifier="command_0x35ECA2"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ECF7"], identifier="command_0x35ECEA"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ECF0"),
	ReturnSubroutine(),
	PlaySound(sound=S0080_WALLOP_1, identifier="command_0x35ECF7"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0081_WALLOP_2),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35ED03"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ED16"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ED0B"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F2BA"], identifier="command_0x35ED11"),
	ReturnSubroutine(),
	RunSubroutine(["command_0x35ED11"], identifier="command_0x35ED16"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35ED21"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ED34"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0016_BOWSER_CLAW_ATTACK, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ED29"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F3E5"]),
	ReturnSubroutine(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0016_BOWSER_CLAW_ATTACK, sequence=1, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ED34"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	PlaySound(sound=S0042_BLADE, identifier="command_0x35ED3E"),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35ED42"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ED55"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F7F9"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0028_GENO_ELBOW_SHOT, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35ED55"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ED63"], identifier="command_0x35ED56"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ED5C"),
	ReturnSubroutine(),
	PlaySound(sound=S0010_MALLOW_PUNCH_1, identifier="command_0x35ED63"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35ED6B"),
	PlaySound(sound=S0048_MALLOW_PUNCH_2),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35ED6F"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35ED83"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F0B4"], identifier="command_0x35ED77"),
	Pause1Frame(identifier="command_0x35ED7B"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0005_MARIO_HAMMER_ATTACK_UP_RIGHT, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F0B4"], identifier="command_0x35ED83"),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0005_MARIO_HAMMER_ATTACK_UP_RIGHT, sequence=1, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35ED8A"),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35ED92"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EDA6"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F61A"]),
	Pause1Frame(identifier="command_0x35ED9E"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0023_MALLOW_SWING_STICK, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F61A"], identifier="command_0x35EDA6"),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0023_MALLOW_SWING_STICK, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EDB5"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EDC8"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F18D"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=4, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35EDC1"),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35EDC8"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EDC9"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EDD4"]),
	Jmp(["command_0x35ECF0"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F0A1"], identifier="command_0x35EDD4"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EDE0"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EDF3"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F862"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0029_GENO_FINGER_SHOT, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35EDF3"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EDF4"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE08"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F66E"], identifier="command_0x35EDFC"),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0023_MALLOW_SWING_STICK, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F66E"], identifier="command_0x35EE08"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2, identifier="command_0x35EE0C"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0023_MALLOW_SWING_STICK, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE18"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE2B"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F3F0"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0017_BOWSER_SWING_BALL_CHAIN, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35EE24"),
	ReturnSubroutine(),
	ClearAMEM8Bit(0x6F, identifier="command_0x35EE2B"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F3F0"]),
	Jmp(["command_0x351195"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE34"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE3F"]),
	Jmp(["command_0x35ED77"]),
	Jmp(["command_0x35ED83"], identifier="command_0x35EE3F"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE42"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE51"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F3F0"]),
	Jmp(["command_0x35EE24"]),
	Jmp(["command_0x35EE2B"], identifier="command_0x35EE51"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE54"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE68"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F139"]),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0005_MARIO_HAMMER_ATTACK_UP_RIGHT, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F139"], identifier="command_0x35EE68"),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0005_MARIO_HAMMER_ATTACK_UP_RIGHT, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE77"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE8A"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35FAB3"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0029_GENO_FINGER_SHOT, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35EE8A"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EE94"], identifier="command_0x35EE8B"),
	Jmp(["command_0x35ED5C"]),
	PlaySound(sound=S0010_MALLOW_PUNCH_1, identifier="command_0x35EE94"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	Jmp(["command_0x35ED6B"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35EE9F"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EEAA"]),
	Jmp(["command_0x35ED0B"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F2BA"], identifier="command_0x35EEAA"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EEB6"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EEC5"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F1D7"]),
	Jmp(["command_0x35EDC1"]),
	ReturnSubroutine(identifier="command_0x35EEC5"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EEC6"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EEDA"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F33A"]),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0011_TOADSTOOL_FRYING_PAN_ATTACK, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F33A"], identifier="command_0x35EEDA"),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0011_TOADSTOOL_FRYING_PAN_ATTACK, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EEE9"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EEFC"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F4F1"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0017_BOWSER_SWING_BALL_CHAIN, sequence=1, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35EEF5"),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x6E, identifier="command_0x35EEFC"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F4F1"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	RunSubroutine(["command_0x35EEF5"]),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35EF08"),
	Jmp(["command_0x351195"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35EF0C"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EF1F"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F832"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0028_GENO_ELBOW_SHOT, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35EF1F"),
	ClearAMEM16Bit(0x60, identifier="command_0x35EF20"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EF2F"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F6FE"]),
	Jmp(["command_0x35ED9E"]),
	ClearAMEM8Bit(0x6F, identifier="command_0x35EF2F"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F6FE"]),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0023_MALLOW_SWING_STICK, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	Jmp(["command_0x35EF08"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35EF41"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EF50"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F479"]),
	Jmp(["command_0x35EE24"]),
	ClearAMEM8Bit(0x6F, identifier="command_0x35EF50"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F479"]),
	Jmp(["command_0x351195"]),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EF66"], identifier="command_0x35EF59"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=5, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	PlaySound(sound=S0084_WALLOP_4, identifier="command_0x35EF66"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT, sequence=6, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0085_WALLOP_5),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EF73"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EF87"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F38E"]),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ClearAMEM8Bit(0x6F, identifier="command_0x35EF87"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F38E"]),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=4, store_to_vram=True, overlap_all_sprites=True),
	Jmp(["command_0x35EF08"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35EF99"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EFAC"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35FB63"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0029_GENO_FINGER_SHOT, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35EFAC"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EFBA"], identifier="command_0x35EFAD"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	PlaySound(sound=S0152_HIT, identifier="command_0x35EFBA"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0022_MALLOW_PUNCH, sequence=4, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0195_EXPLOSIVE_HIT),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EFC6"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EFD5"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F25D"]),
	Jmp(["command_0x35ED7B"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F25D"], identifier="command_0x35EFD5"),
	RunSubroutine(["command_0x358117"]),
	RunSubroutine(["command_0x35ED8A"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35EFE7"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35EFFA"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35F2BA"]),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F2BA"], identifier="command_0x35EFFA"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0010_TOADSTOOL_SLAP_ATTACK, sequence=2, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35F007"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F012"]),
	Jmp(["command_0x35ED29"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0016_BOWSER_CLAW_ATTACK, sequence=2, store_to_vram=True, overlap_all_sprites=True, identifier="command_0x35F012"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PlaySound(sound=S0042_BLADE),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PlaySound(sound=S0042_BLADE),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	Jmp(["command_0x35ED3E"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35F02B"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F03E"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35FBA2"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0029_GENO_FINGER_SHOT, sequence=3, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	ReturnSubroutine(identifier="command_0x35F03E"),
	ClearAMEM16Bit(0x60, identifier="command_0x35F03F"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F04A"]),
	Jmp(["command_0x35EDFC"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35F66E"], identifier="command_0x35F04A"),
	Jmp(["command_0x35EE0C"]),
	ClearAMEM16Bit(0x60, identifier="command_0x35F051"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F060"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F21A"]),
	Jmp(["command_0x35EDC1"]),
	ReturnSubroutine(identifier="command_0x35F060"),
	ClearAMEM16Bit(0x60, identifier="command_0x35F061"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F075"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["command_0x35F2E6"]),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0011_TOADSTOOL_FRYING_PAN_ATTACK, sequence=0, store_to_vram=True, overlap_all_sprites=True),
	ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F2E6"], identifier="command_0x35F075"),
	RunSubroutine(["command_0x358117"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0011_TOADSTOOL_FRYING_PAN_ATTACK, sequence=1, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	ClearAMEM16Bit(0x60, identifier="command_0x35F084"),
	JmpIfAMEM8BitEqualsConst(0x62, 1, ["command_0x35F08F"]),
	Jmp(["command_0x35ED77"]),
	ClearAMEM8Bit(0x6F, identifier="command_0x35F08F"),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35F0B4"]),
	Pause1Frame(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=10, store_to_vram=True, overlap_all_sprites=True),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	PauseScriptUntilSpriteSequenceDone(),
	ReturnSubroutine(),
	DefineObjectQueue(["command_0x35F0A3"], identifier="command_0x35F0A1"),
	DefineObjectQueue(["command_0x35F0A5"], identifier="command_0x35F0A3"),
	PlaySound(sound=S0080_WALLOP_1, identifier="command_0x35F0A5"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	PlaySound(sound=S0081_WALLOP_2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	PlaySound(sound=S0082_WALLOP_3),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F0B6"], identifier="command_0x35F0B4"),
	DefineObjectQueue(["command_0x35F0BC", "command_0x35F0DF", "command_0x35F10D"], identifier="command_0x35F0B6"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F0BC"),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F0CE"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F0CE"]),
	RemoveObject(identifier="command_0x35F0D9"),
	SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x63),
	ReturnObjectQueue(),
	PlaySound(sound=S0054_HAMMER_HIT_1, identifier="command_0x35F0DF"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F0E9"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F0E9"]),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0055_HAMMER_HIT_2),
	Pause1Frame(identifier="command_0x35F100"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F100"]),
	RemoveObject(),
	ReturnObjectQueue(),
	PlaySound(sound=S0054_HAMMER_HIT_1, identifier="command_0x35F10D"),
	Pause1Frame(identifier="command_0x35F10F"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F10F"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=4, y=-38, z=0, set_x=True, set_y=True, set_z=True),
	InitializeBonusMessageSequence(),
	PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
	DisplayBonusMessage(message=BM_LUCKY, x=0, y=6),
	PauseScriptUntilBonusMessageComplete(),
	SetAMEM8BitToAbsolute7E(0x6F, 0x7EFA1F),
	SetAMEMBits(0x6F, [0]),
	SetAbsolute7EToAMEM8Bit(0x7EFA1F, 0x6F),
	Jmp(["command_0x352528"]),
	DefineObjectQueue(["command_0x35F13B"], identifier="command_0x35F139"),
	DefineObjectQueue(["command_0x35F13F", "command_0x35F15F"], identifier="command_0x35F13B"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F13F"),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=2, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F151"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F151"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0054_HAMMER_HIT_1, identifier="command_0x35F15F"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F169"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F169"]),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=3, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0055_HAMMER_HIT_2),
	Pause1Frame(identifier="command_0x35F180"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F180"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F18F"], identifier="command_0x35F18D"),
	DefineObjectQueue(["command_0x35F191"], identifier="command_0x35F18F"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-12, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F191"),
	NewSpriteAtCoords(sprite_id=SPR0540_GREEN_LAZY_SHELL_TUB_O_TROOPA, sequence=2, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1),
	MoveObject(speed=161, start_position=-2561, end_position=2560, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=-6, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1920, arch_height=0),
	PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0540_GREEN_LAZY_SHELL_TUB_O_TROOPA, sequence=2, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x357EE2"], identifier="command_0x35F1CD"),
	SetAMEM8BitToConst(0x67, 1),
	Jmp(["command_0x354D68"]),
	DefineObjectQueue(["command_0x35F1D9"], identifier="command_0x35F1D7"),
	DefineObjectQueue(["command_0x35F1DB"], identifier="command_0x35F1D9"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-12, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F1DB"),
	NewSpriteAtCoords(sprite_id=SPR0539_ORANGE_LAZY_SHELL, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1),
	MoveObject(speed=161, start_position=-2561, end_position=2560, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=-6, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1920, arch_height=0),
	PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0539_ORANGE_LAZY_SHELL, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x35F1CD"]),
	DefineObjectQueue(["command_0x35F21C"], identifier="command_0x35F21A"),
	DefineObjectQueue(["command_0x35F21E"], identifier="command_0x35F21C"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=10, y=-12, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F21E"),
	NewSpriteAtCoords(sprite_id=SPR0538_LAZY_SHELL_HEAVY_TROOPA_NOK_NOK_SHELL, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PlaySound(sound=S0192_BIG_SHELL_KICK),
	MoveObject(speed=49, start_position=-769, end_position=768, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Pause1Frame(),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=-6, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1920, arch_height=0),
	PlaySound(sound=S0193_BIG_SHELL_HIT_1),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0538_LAZY_SHELL_HEAVY_TROOPA_NOK_NOK_SHELL, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	Jmp(["command_0x35F1CD"]),
	DefineObjectQueue(["command_0x35F25F"], identifier="command_0x35F25D"),
	DefineObjectQueue(["command_0x35F263", "command_0x35F283"], identifier="command_0x35F25F"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F263"),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F275"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F275"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0054_HAMMER_HIT_1, identifier="command_0x35F283"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F28D"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F28D"]),
	NewSpriteAtCoords(sprite_id=SPR0031_HAMMER, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0055_HAMMER_HIT_2),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0031_HAMMER, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0054_HAMMER_HIT_1),
	Pause1Frame(identifier="command_0x35F2AD"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F2AD"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F2BC"], identifier="command_0x35F2BA"),
	DefineObjectQueue(["command_0x35F2C4", "command_0x35F2CF", "command_0x35F2D5", "command_0x35F2E0"], identifier="command_0x35F2BC"),
	RunSubroutine(["command_0x357D34"], identifier="command_0x35F2C4"),
	PlaySound(sound=S0160_SLAP),
	RunSubroutine(["command_0x358121"]),
	PlaySound(sound=S0160_SLAP),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x358130"], identifier="command_0x35F2CF"),
	PlaySound(sound=S0171_SLAP_POWERFUL),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x357D34"], identifier="command_0x35F2D5"),
	PlaySound(sound=S0171_SLAP_POWERFUL),
	RunSubroutine(["command_0x358121"]),
	PlaySound(sound=S0171_SLAP_POWERFUL),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x35813A"], identifier="command_0x35F2E0"),
	PlaySound(sound=S0084_WALLOP_4),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F2E8"], identifier="command_0x35F2E6"),
	DefineObjectQueue(["command_0x35F2EC", "command_0x35F30C"], identifier="command_0x35F2E8"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F2EC"),
	NewSpriteAtCoords(sprite_id=SPR0035_FRYING_PAN, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F2FE"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F2FE"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0083_FRYING_PAN_HIT_1, identifier="command_0x35F30C"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F316"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F316"]),
	NewSpriteAtCoords(sprite_id=SPR0035_FRYING_PAN, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0038_FRYING_PAN_HIT_2),
	Pause1Frame(identifier="command_0x35F32D"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F32D"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F33C"], identifier="command_0x35F33A"),
	DefineObjectQueue(["command_0x35F340", "command_0x35F360"], identifier="command_0x35F33C"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F340"),
	NewSpriteAtCoords(sprite_id=SPR0036_PARASOL, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F352"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F352"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0046_PLASMA_BOUNCE, identifier="command_0x35F360"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F36A"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F36A"]),
	NewSpriteAtCoords(sprite_id=SPR0036_PARASOL, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0047_DRY_CLUNK),
	Pause1Frame(identifier="command_0x35F381"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F381"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F390"], identifier="command_0x35F38E"),
	DefineObjectQueue(["command_0x35F394", "command_0x35F3B4"], identifier="command_0x35F390"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F394"),
	NewSpriteAtCoords(sprite_id=SPR0037_WAR_FAN, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F3A6"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F3A6"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0160_SLAP, identifier="command_0x35F3B4"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F3BE"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F3BE"]),
	NewSpriteAtCoords(sprite_id=SPR0037_WAR_FAN, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0171_SLAP_POWERFUL),
	RunSubroutine(["command_0x35884B"]),
	Pause1Frame(identifier="command_0x35F3D8"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F3D8"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F3E7"], identifier="command_0x35F3E5"),
	DefineObjectQueue(["command_0x35F3E9"], identifier="command_0x35F3E7"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=28, identifier="command_0x35F3E9"),
	PlaySound(sound=S0039_CLAW),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F3F2"], identifier="command_0x35F3F0"),
	DefineObjectQueue(["command_0x35F3F6", "command_0x35F444"], identifier="command_0x35F3F2"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F3F6"),
	NewSpriteAtCoords(sprite_id=SPR0034_CHOMP, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=48, y=-32, z=0, set_x=True, set_y=True, set_z=True),
	SpriteSequence(sequence=1),
	ResetTargetMappingMemory(identifier="command_0x35F423"),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	SetAMEM8BitToConst(0x67, 1),
	SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10, identifier="command_0x35F43E"),
	RemoveObject(),
	ReturnObjectQueue(),
	PlaySound(sound=S0122_POISONED, identifier="command_0x35F444"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0034_CHOMP, sequence=2, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35811C"], identifier="chomp_subroutine"),
	PlaySound(sound=S0123_CHOMP_BITE),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0123_CHOMP_BITE),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0123_CHOMP_BITE),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0123_CHOMP_BITE),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0042_BLADE),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	Jmp(["command_0x35932E"]),
	DefineObjectQueue(["command_0x35F47B"], identifier="command_0x35F479"),
	DefineObjectQueue(["command_0x35F47F", "command_0x35F4AF"], identifier="command_0x35F47B"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F47F"),
	NewSpriteAtCoords(sprite_id=SPR0034_CHOMP, sequence=3, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0121_BIG_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=48, y=-32, z=0, set_x=True, set_y=True, set_z=True),
	SpriteSequence(sequence=4),
	Jmp(["command_0x35F423"]),
	PlaySound(sound=S0137_BOWSER_CRUSH_STOMP, identifier="command_0x35F4AF"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0034_CHOMP, sequence=5, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True),
	UnknownCommand(bytearray([0xE5, 0x01])),
	ScreenFlashWithDuration(WHITE, 1, 16),
	PlaySound(sound=S0042_BLADE),
	RunSubroutine(["command_0x35812B"]),
	SpriteSequence(sequence=4, looping_off=True),
	RunSubroutine(["command_0x358126"]),
	SpriteSequence(sequence=5, looping_off=True),
	ScreenFlashWithDuration(WHITE, 1, 16),
	PlaySound(sound=S0042_BLADE),
	RunSubroutine(["command_0x35812B"]),
	SpriteSequence(sequence=4, looping_off=True),
	RunSubroutine(["command_0x358126"]),
	SpriteSequence(sequence=5, looping_off=True),
	ScreenFlashWithDuration(WHITE, 1, 16),
	PlaySound(sound=S0042_BLADE),
	RemoveObject(),
	SetAMEM8BitToConst(0x6F, 1),
	Jmp(["command_0x35BF78"]),
	DefineObjectQueue(["command_0x35F4F3"], identifier="command_0x35F4F1"),
	DefineObjectQueue(["command_0x35F4F9", "command_0x35F56C", "command_0x35F5F8"], identifier="command_0x35F4F3"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13, identifier="command_0x35F4F9"),
	SetAMEM16BitToConst(0x60, 64384),
	SetAbsolute7EToAMEM16Bit(0x7EE022, 0x60),
	SetAMEM8BitToUnknownShort(amem=0x6F, type=0xB, value=0x0000),
	IncAMEM8BitByUnknownShort(amem=0x6F, type=0xB, value=0x0040),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F522"]),
	UseSpriteQueue(field_object=0, destinations=["command_0x35F616"], character_slot=True, bit_5=True),
	ClearAMEM16Bit(0x60),
	SetAbsolute7EToAMEM8Bit(0x7EE025, 0x60),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35F4F1"]),
	RunSubroutine(["command_0x35D2DE"], identifier="command_0x35F522"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-21, z=0, set_x=True, set_y=True, set_z=True),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F53F"]),
	NewSpriteAtCoords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=4, priority=3, vram_address=0x6600, palette_row=6, overwrite_vram=True, looping=True, mirror_sprite=True, overlap_all_sprites=True),
	Jmp(["command_0x35F548"]),
	NewSpriteAtCoords(sprite_id=SPR0096_MARIO_DOLL_SURPRISED, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True, identifier="command_0x35F53F"),
	RunSubroutine(["command_0x358121"], identifier="command_0x35F548"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F567"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=8, store_to_vram=True, overlap_all_sprites=True),
	PlaySound(sound=S0092_SPEAR_RAIN_SINGLE, identifier="command_0x35F567"),
	Jmp(["command_0x35F1CD"]),
	PlaySound(sound=S0159_BIG_DEEP_HIT, identifier="command_0x35F56C"),
	SetAMEM16BitToConst(0x60, 64384),
	SetAMEM8BitToUnknownShort(amem=0x6F, type=0xB, value=0x0000),
	IncAMEM8BitByUnknownShort(amem=0x6F, type=0xB, value=0x0040),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F595"]),
	NewSpriteAtCoords(sprite_id=SPR0003_MARIO_SURPRISE_LEFT, sequence=6, priority=3, vram_address=0x6600, palette_row=6, overwrite_vram=True, overlap_all_sprites=True),
	Jmp(["command_0x35F59E"]),
	NewSpriteAtCoords(sprite_id=SPR0096_MARIO_DOLL_SURPRISED, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True, identifier="command_0x35F595"),
	ResetTargetMappingMemory(identifier="command_0x35F59E"),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-21, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=256),
	RunSubroutine(["command_0x357EE2"]),
	SetAMEM8BitToConst(0x6E, 1),
	RunSubroutine(["command_0x35B4D4"]),
	RunSubroutine(["command_0x358130"]),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F5C6"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=4, store_to_vram=True, looping=True, overlap_all_sprites=True, bit_7=True),
	RunSubroutine(["command_0x358121"], identifier="command_0x35F5C6"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35F5E5"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=8, store_to_vram=True, overlap_all_sprites=True),
	PlaySound(sound=S0092_SPEAR_RAIN_SINGLE, identifier="command_0x35F5E5"),
	RunSubroutine(["command_0x357EE2"]),
	PlaySound(sound=S0159_BIG_DEEP_HIT),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	PlaySound(sound=S0159_BIG_DEEP_HIT),
	RunSubroutine(["command_0x35884B"]),
	Jmp(["command_0x35F43E"]),
	UnknownCommand(bytearray([0xA6]), identifier="command_0x35F5F8"),
	SetAMEM16BitToAbsolute7E(0x60, 0x7EE022),
	RunSubroutine(["command_0x352702"]),
	NewSpriteAtCoords(sprite_id=SPR0096_MARIO_DOLL_SURPRISED, sequence=2, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, param_2_and_0x10=True, overwrite_palette=True, overlap_all_sprites=True),
	Pause1Frame(identifier="command_0x35F609"),
	SetAMEM8BitToAbsolute7E(0x6F, 0x7EE025),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35F609"]),
	RemoveObject(),
	ReturnObjectQueue(),
	UnknownCommand(bytearray([0x89]), identifier="command_0x35F616"),
	ReturnSpriteQueue(),
	UnknownCommand(bytearray([0x88]), identifier="command_0x35F618"),
	ReturnSpriteQueue(),
	DefineObjectQueue(["command_0x35F61C"], identifier="command_0x35F61A"),
	DefineObjectQueue(["command_0x35F620", "command_0x35F640"], identifier="command_0x35F61C"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F620"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F632"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F632"]),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1, identifier="command_0x35F640"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F64A"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F64A"]),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
	Pause1Frame(identifier="command_0x35F661"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F661"]),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F670"], identifier="command_0x35F66E"),
	DefineObjectQueue(["command_0x35F676", "command_0x35F69B", "command_0x35F6C7"], identifier="command_0x35F670"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F676"),
	NewSpriteAtCoords(sprite_id=SPR0033_CYMBALS, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35812B"]),
	PlaySound(sound=S0049_CYMBAL_CRASH),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F68D"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F68D"]),
	Jmp(["command_0x35F0D9"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F69B"),
	Pause1Frame(identifier="command_0x35F6A3"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F6A3"]),
	NewSpriteAtCoords(sprite_id=SPR0033_CYMBALS, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PlaySound(sound=S0060_CYMBAL_RESONANCE),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F6BA"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F6BA"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F6C7"),
	Pause1Frame(identifier="command_0x35F6CF"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F6CF"]),
	NewSpriteAtCoords(sprite_id=SPR0033_CYMBALS, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PlaySound(sound=S0060_CYMBAL_RESONANCE),
	WaveEffect(layer=WAVE_LAYER_BATTLEFIELD, direction=WAVE_LAYER_HORIZONTAL, depth=16, intensity=8, speed=240),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F6EF"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F6EF"]),
	StopWaveEffect(),
	RemoveObject(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F700"], identifier="command_0x35F6FE"),
	DefineObjectQueue(["command_0x35F70C", "command_0x35F745", "command_0x35F795", "command_0x35F7B3", "command_0x35F7D1", "command_0x35F7E5"], identifier="command_0x35F700"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F70C"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x357947"]),
	ClearAMEM16Bit(0x60),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35F6FE"]),
	RunSubroutine(["command_0x357947"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F6FE"]),
	RunSubroutine(["command_0x358130"]),
	PlaySound(sound=S0112_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35F733"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35F733"]),
	SetAbsolute7EToAMEM8Bit(0x7EE020, 0x63),
	Jmp(["command_0x35F0D9"]),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1, identifier="command_0x35F745"),
	ClearAMEM16Bit(0x60),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35F751"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35F751"]),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x357947"]),
	ClearAMEM8Bit(0x6E),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35F6FE"]),
	RunSubroutine(["command_0x357947"]),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35F6FE"]),
	RunSubroutine(["command_0x358126"]),
	PlaySound(sound=S0112_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	RunSubroutine(["command_0x35884F"]),
	Pause1Frame(identifier="command_0x35F788"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35F788"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F795"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Pause1Frame(identifier="command_0x35F7A6"),
	SetAMEM8BitToAbsolute7E(0x6E, 0x7EE020),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35F7A6"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F7B3"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Pause1Frame(identifier="command_0x35F7C4"),
	SetAMEM8BitToAbsolute7E(0x6E, 0x7EE020),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35F7C4"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F7D1"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Jmp(["command_0x35B619"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F7E5"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Jmp(["command_0x35DA89"]),
	DefineObjectQueue(["command_0x35F7FB"], identifier="command_0x35F7F9"),
	DefineObjectQueue(["command_0x35F7FD"], identifier="command_0x35F7FB"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=46, identifier="command_0x35F7FD"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=18, y=-18, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0028_GENO_ELBOW_SHOT, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0051_FIRE_THROW_BIG),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"], identifier="command_0x35F824"),
	RemoveObject(),
	SetAMEM8BitToConst(0x66, 1),
	SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
	ResetObjectMappingMemory(),
	ReturnObjectQueue(),
	DefineObjectQueue(["command_0x35F834"], identifier="command_0x35F832"),
	DefineObjectQueue(["command_0x35F836"], identifier="command_0x35F834"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=34, identifier="command_0x35F836"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=-20, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0028_GENO_ELBOW_SHOT, sequence=3, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(sound=S0051_FIRE_THROW_BIG),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	PlaySound(sound=S0051_FIRE_THROW_BIG),
	Jmp(["command_0x35F824"]),
	DefineObjectQueue(["command_0x35F864"], identifier="command_0x35F862"),
	DefineObjectQueue(["command_0x35F874", "command_0x35F8D6", "command_0x35F947", "command_0x35F982", "command_0x35F9A7", "command_0x35F9CC", "command_0x35F9EB", "command_0x35FA4C"], identifier="command_0x35F864"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30, identifier="command_0x35F874"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=236, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	PlaySound(sound=S0052_FINGER_SHOT_BULLETS),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=22, y=237, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=24, y=238, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=26, y=239, z=0, set_x=True, set_y=True, set_z=True),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	Pause1Frame(identifier="command_0x35F8C5"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 4, ["command_0x35F8C5"]),
	RemoveObject(identifier="command_0x35F8CC"),
	SetAMEM8BitToConst(0x66, 1),
	SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
	ReturnObjectQueue(),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35F8D6"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM16BitToUnknownShort(amem=0x6C, type=0x9, value=0x003A),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35F909"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-18, y=-5, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=48),
	Jmp(["command_0x35F917"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-18, y=24, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F909"),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=160, arch_height=24),
	RunSubroutine(["command_0x358091"], identifier="command_0x35F917"),
	SetAMEM60ToCurrentTarget(),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35F92C"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-24, y=-6, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35F934"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-24, y=25, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F92C"),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128, identifier="command_0x35F934"),
	RunSubroutine(["command_0x357EE2"], identifier="command_0x35F93A"),
	RemoveObject(),
	SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
	IncAMEM8Bit(0x6F),
	Jmp(["command_0x352528"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=3, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35F947"),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=4, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F862"]),
	Pause1Frame(identifier="command_0x35F978"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 4, ["command_0x35F978"]),
	Jmp(["command_0x35A88E"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35F982"),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=13, y=-236, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=256, arch_height=128),
	RunSubroutine(["command_0x358091"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=19, y=-232, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=112, arch_height=128),
	Jmp(["command_0x35F93A"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35F9A7"),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=9, y=-233, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=288, arch_height=160),
	RunSubroutine(["command_0x358091"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=6, y=-231, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128, identifier="command_0x35F9C3"),
	Jmp(["command_0x35F93A"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35F9CC"),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=17, y=-238, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=288, arch_height=128),
	RunSubroutine(["command_0x358091"]),
	SetAMEM40ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=21, y=-239, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35F9C3"]),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35F9EB"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM16BitToUnknownShort(amem=0x6C, type=0x9, value=0x003A),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35FA1E"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=5, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=80),
	Jmp(["command_0x35FA2C"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=24, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FA1E"),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=160, arch_height=40),
	RunSubroutine(["command_0x358091"], identifier="command_0x35FA2C"),
	SetAMEM60ToCurrentTarget(),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35FA41"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=8, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35FA49"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=27, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FA41"),
	Jmp(["command_0x35F9C3"], identifier="command_0x35FA49"),
	RunSubroutine(["command_0x35E372"], identifier="command_0x35FA4C"),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM16BitToUnknownShort(amem=0x6C, type=0x9, value=0x003A),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35FA7F"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=16, y=-1, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=32),
	Jmp(["command_0x35FA8D"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=16, y=17, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FA7F"),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=16),
	RunSubroutine(["command_0x358091"], identifier="command_0x35FA8D"),
	SetAMEM60ToCurrentTarget(),
	JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35FAA2"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=24, y=3, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35FAAA"]),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=24, y=21, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FAA2"),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=144, arch_height=128, identifier="command_0x35FAAA"),
	Jmp(["command_0x35F93A"]),
	DefineObjectQueue(["command_0x35FAB5"], identifier="command_0x35FAB3"),
	DefineObjectQueue(["command_0x35FAB9", "command_0x35FB18"], identifier="command_0x35FAB5"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30, identifier="command_0x35FAB9"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=239, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35FAB3"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F862"]),
	RunSubroutine(["command_0x35811C"]),
	PlaySound(sound=S0000_SILENCE),
	Pause1Frame(identifier="command_0x35FB0B"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35FB0B"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	Jmp(["command_0x35F8CC"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=3, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FB18"),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=4, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=8, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=10, destinations=["command_0x35F862"]),
	Pause1Frame(identifier="command_0x35FB59"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35FB59"]),
	Jmp(["command_0x35A88E"]),
	DefineObjectQueue(["command_0x35FB65"], identifier="command_0x35FB63"),
	DefineObjectQueue(["command_0x35FB67"], identifier="command_0x35FB65"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50, identifier="command_0x35FB67"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=240, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=2, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6F),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F862"]),
	PlaySound(sound=S0109_GENO_HAND_CANNON_SHOOT),
	RunSubroutine(["command_0x35811C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35F862"]),
	PlaySound(sound=S0109_GENO_HAND_CANNON_SHOOT),
	RunSubroutine(["command_0x35811C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	PlaySound(sound=S0109_GENO_HAND_CANNON_SHOOT),
	Pause1Frame(identifier="command_0x35FB98"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 3, ["command_0x35FB98"]),
	Jmp(["command_0x35F8CC"]),
	DefineObjectQueue(["command_0x35FBA4"], identifier="command_0x35FBA2"),
	DefineObjectQueue(["command_0x35FBAC", "command_0x35FBFB", "command_0x35FC37", "command_0x35FC73"], identifier="command_0x35FBA4"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50, identifier="command_0x35FBAC"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=240, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=3, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6F),
	PlaySound(sound=S0017_STAR_GUN_SHOOT),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x35FBA2"]),
	RunSubroutine(["command_0x35811C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=14, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=4, destinations=["command_0x35FBA2"]),
	RunSubroutine(["command_0x35811C"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=12, destinations=["command_0x35F862"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["command_0x35FBA2"]),
	Pause1Frame(identifier="command_0x35FBF1"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35FBF1"]),
	Jmp(["command_0x35F8CC"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-260, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FBFB"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-12, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-18, y=-5, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=48),
	RunSubroutine(["command_0x358091"]),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-24, y=-6, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35F9C3"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-260, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FC37"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-12, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=5, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=80),
	RunSubroutine(["command_0x358091"]),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=8, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35F9C3"]),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-6, y=-260, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x35FC73"),
	UnknownCommand(bytearray([0x83, 0x83])),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-4, y=-12, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
	RunSubroutine(["command_0x357A67"]),
	ResetTargetMappingMemory(),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=16, y=-1, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=32),
	RunSubroutine(["command_0x358091"]),
	SetAMEM60ToCurrentTarget(),
	SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=24, y=3, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x35FAAA"]),
    NewEffectObject(effect=EF0036_BLANK_WHITE_FLASH_2BPP, playback_off=True, identifier="base_wpn_subroutine"),
    SetAMEM8BitToConst(0x6F, 100),
    Set7FToAMEM8Bit(0x7FFFB0, 0x6F),
    ReturnSubroutine(),
    
	ClearAMEM16Bit(0x60, identifier="stella023_weapon"),
    JmpIfAMEM8BitEqualsConst(amem=0x62, value=1, destinations=["exit"]),
    UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["postgame_weapons_top"]),
    DrawSpriteAtAMEM32Coords(sprite_id=30, sequence=2, store_to_vram=True, overlap_all_sprites=True),
    ReturnSubroutine(identifier="exit"),
    
	DefineObjectQueue(["stella_023_subroutine_addr"], identifier="postgame_weapons_top"),
	DefineObjectQueue(["stella_023_subroutine"], identifier="stella_023_subroutine_addr"),
    PauseScriptUntil(FRAMES_ELAPSED, 40, identifier="stella_023_subroutine"),
    SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=26, y=-11, z=0, set_x=True, set_y=True, set_z=True, identifier="stella_023_main"),
    NewSpriteAtCoords(sprite_id=578, sequence=0, overwrite_vram=True, palette_row=8, vram_address=0x6400, priority=3, overwrite_palette=True, overlap_all_sprites=True),
	PlaySound(S0063_GENO_BLAST_IGNITION),
    PauseScriptUntil(FRAMES_ELAPSED, 25),
    PlaySound(S0095_BOWSERS_CRUSHER),
    PauseScriptUntil(FRAMES_ELAPSED, 10),
    RemoveObject(),
    SetAMEM8BitToConst(amem=0x66, value=1),
    SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
    ResetObjectMappingMemory(),
    ReturnObjectQueue(),
    
    
	ClearAMEM16Bit(0x60, identifier="sagestick_weapon"),
    Pause1Frame(),
    JmpIfAMEM8BitEqualsConst(amem=0x62, value=1, destinations=["sagestick_init_subroutine"]),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=2, destinations=["postgame_2_weapons_top"]),
    Pause1Frame(),
    DrawSpriteAtAMEM32Coords(sprite_id=23, sequence=0, store_to_vram=True),
    ReturnSubroutine(),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["postgame_2_weapons_top"], identifier="sagestick_init_subroutine"),
	PauseScriptUntil(FRAMES_ELAPSED, 3),
    DrawSpriteAtAMEM32Coords(sprite_id=23, sequence=1, store_to_vram=True),
	PauseScriptUntilSpriteSequenceDone(),
    ReturnSubroutine(),
    
	DefineObjectQueue(["sagestick_subroutine_addr"], identifier="postgame_2_weapons_top"),
	DefineObjectQueue(["sagestick_subroutine", "sagestick_subroutine_2"], identifier="sagestick_subroutine_addr"),
	PlaySound(S0018_SUPER_JUMP_HIT_1, identifier="sagestick_subroutine"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-0, z=0, set_x=True, set_y=True, set_z=True),
    Pause1Frame(identifier="sagestick_pause_loop"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
    JmpIfAMEM8BitNotEqualsConst(amem=0x64, value=1, destinations=["sagestick_pause_loop"]),
    NewSpriteAtCoords(sprite_id=576, sequence=1, palette_row=8, vram_address=0x6600, priority=3, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True, behind_all_sprites=True),
    PauseScriptUntilSpriteSequenceDone(),
    PlaySound(S0058_SUPER_JUMP_HIT_2),
    Pause1Frame(identifier="sagestick_pause_loop_2"),
    SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
    JmpIfAMEM8BitNotEqualsConst(amem=0x65, value=1, destinations=["sagestick_pause_loop_2"]),
    RemoveObject(),
    ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=-0, z=0, set_x=True, set_y=True, set_z=True, identifier="sagestick_subroutine_2"),
	NewSpriteAtCoords(sprite_id=576, sequence=0, palette_row=8, vram_address=0x6600, priority=3, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True, behind_all_sprites=True),
    PauseScriptUntilSpriteSequenceDone(),
    Pause1Frame(identifier="sagestick_pause_loop_3"),
    SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
    JmpIfAMEM8BitNotEqualsConst(amem=0x63, value=1, destinations=["sagestick_pause_loop_3"]),
    RemoveObject(),
    SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x63),
    ReturnObjectQueue(),
    

	
	ClearAMEM16Bit(0x60, identifier="wonderchomp_weapon"),
    JmpIfAMEM8BitEqualsConst(amem=0x62, value=1, destinations=["wonderchomp_branch_1"]),
    UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=0, destinations=["wonderchomp_oq_upper"]),
    DrawSpriteAtAMEM32Coords(sprite_id=17, sequence=0, store_to_vram=True, overlap_all_sprites=True, identifier="DrawBowser17Seq0"),
    ReturnSubroutine(),
    
    DefineObjectQueue(["wonderchomp_oq_lower"], identifier="wonderchomp_oq_upper"),
    DefineObjectQueue(["wonderchomp_branch_2", "wonderchomp_branch_1.5"], identifier="wonderchomp_oq_lower"),
    PlaySound(S0122_POISONED, identifier="wonderchomp_branch_1.5"),
    ResetTargetMappingMemory(),
    SetAMEM60ToCurrentTarget(),
    SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
    NewSpriteAtCoords(577, sequence=6, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
    RunSubroutine(["chomp_subroutine"]),
    ReturnObjectQueue(),
    SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="wonderchomp_branch_2"),
    NewSpriteAtCoords(577, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
    RunSubroutine(["chomp_subroutine_swing"]),
    SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=40, y=-32, z=0, set_x=True, set_y=True, set_z=True),
    SpriteSequence(1),
    ResetTargetMappingMemory(),
    SetAMEM60ToCurrentTarget(),
    SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-8, z=0, set_x=True, set_y=True, set_z=True),
    MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
    PauseScriptUntil(UNKNOWN_PAUSE_7),
    SetAMEM8BitToConst(amem=0x67, value=1),
    SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
    PauseScriptUntil(FRAMES_ELAPSED, 10),
	RemoveObject(),
    ReturnObjectQueue(),
    PlaySound(S0121_BIG_SWING, identifier="chomp_subroutine_swing"),
    PauseScriptUntil(FRAMES_ELAPSED, 15),
    PlaySound(S0121_BIG_SWING),
    PauseScriptUntil(FRAMES_ELAPSED, 15),
    PlaySound(S0121_BIG_SWING),
    PauseScriptUntil(FRAMES_ELAPSED, 15),
    PlaySound(S0121_BIG_SWING),
    PauseScriptUntilSpriteSequenceDone(),
    ReturnSubroutine(),
])
