# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=1415, expected_beginning=0x3AC1F1, script=[
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC1F1"),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A7200"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0001_MARIO_JUMP_FRONT, sequence=4, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True, bit_7=True),
	RunSubroutine(["command_0x3A733C"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=1, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True, bit_7=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	Jmp(["command_0x3ABE4E"]),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3AC22D"),
	ClearAMEM8Bit(0x60),
	SetAMEM8BitToConst(0x60, 128),
	SetAbsolute7EToAMEM8Bit(0x7EFB00, 0x60),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A8124"]),
	RunSubroutine(["command_0x3A72DD"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	ClearAMEM8Bit(0x68),
	SetAMEM8BitToRAMRelative7E(0x60, 0x7E0001),
	JmpIfAMEM8BitEqualsConst(0x60, 2, ["command_0x3AC253"]),
	Jmp(["command_0x3AC2D3"]),
	UnknownCommand(bytearray([0x16]), identifier="command_0x3AC253"),
	Pause1Frame(),
	SetAMEM8BitToAbsolute7E(0x67, 0x7EE003),
	JmpIfAMEMBitsSet(0x67, [0], ["command_0x3AC299"]),
	Pause1Frame(),
	SetAMEMToRandomByte(amem=0x68, upper_bound=100),
	JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3AC27F"]),
	JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3AC287"]),
	JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3AC28A"]),
	JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3AC290"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True, identifier="command_0x3AC27A"),
	Jmp(["command_0x3AC253"]),
	SpriteSequence(sequence=3, looping_off=True, mirror=True, identifier="command_0x3AC27F"),
	RunSubroutine(["command_0x3A7359"]),
	Jmp(["command_0x3AC27A"]),
	Jmp(["command_0x3AC27F"], identifier="command_0x3AC287"),
	SpriteSequence(sequence=5, mirror=True, identifier="command_0x3AC28A"),
	PauseScriptUntilSpriteSequenceDone(),
	Jmp(["command_0x3AC253"]),
	SpriteSequence(sequence=12, mirror=True, identifier="command_0x3AC290"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	Jmp(["command_0x3AC253"]),
	SetAMEM8BitToAbsolute7E(0x60, 0x7EFA80, identifier="command_0x3AC299"),
	ClearAMEMBits(0x60, [7]),
	SetAbsolute7EToAMEM8Bit(0x7EFA80, 0x60),
	SetAMEM8BitToAbsolute7E(0x60, 0x7EFB00),
	ClearAMEMBits(0x60, [7]),
	SetAbsolute7EToAMEM8Bit(0x7EFB00, 0x60),
	ReturnSpriteQueue(),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3AC2B0"),
	ClearAMEM8Bit(0x60),
	SetAMEM8BitToConst(0x60, 128),
	SetAbsolute7EToAMEM8Bit(0x7EFA80, 0x60),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A81C4"]),
	RunSubroutine(["command_0x3A72DD"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	ClearAMEM8Bit(0x68),
	SetAMEM8BitToRAMRelative7E(0x60, 0x7E0001),
	JmpIfAMEM8BitEqualsConst(0x60, 2, ["command_0x3AC253"]),
	UnknownCommand(bytearray([0x16]), identifier="command_0x3AC2D3"),
	Pause1Frame(),
	SetAMEM8BitToAbsolute7E(0x67, 0x7EE003),
	JmpIfAMEMBitsSet(0x67, [0], ["command_0x3AC31B"]),
	Pause1Frame(),
	SetAMEMToRandomByte(amem=0x68, upper_bound=100),
	JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3AC2FF"]),
	JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3AC307"]),
	JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3AC30D"]),
	JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3AC312"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True, identifier="command_0x3AC2FA"),
	Jmp(["command_0x3AC2D3"]),
	SpriteSequence(sequence=3, looping_off=True, mirror=True, identifier="command_0x3AC2FF"),
	RunSubroutine(["command_0x3A7359"]),
	Jmp(["command_0x3AC2FA"]),
	SpriteSequence(sequence=4, mirror=True, identifier="command_0x3AC307"),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x3AC309"),
	Jmp(["command_0x3AC2D3"]),
	SpriteSequence(sequence=5, mirror=True, identifier="command_0x3AC30D"),
	Jmp(["command_0x3AC309"]),
	SpriteSequence(sequence=12, mirror=True, identifier="command_0x3AC312"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	Jmp(["command_0x3AC2D3"]),
	Jmp(["command_0x3AC299"], identifier="command_0x3AC31B"),
	RunSubroutine(["command_0x3A8322"], identifier="command_0x3AC31E"),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 152),
	SetAMEM8BitToConst(0x61, 104),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	Jmp(["command_0x3AA879"]),
	RunSubroutine(["command_0x3A82B4"], identifier="command_0x3AC337"),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 200),
	SetAMEM8BitToConst(0x61, 160),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30, identifier="command_0x3AC34D"),
	Jmp(["command_0x3AA833"]),
	ResetTargetMappingMemory(identifier="command_0x3AC354"),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 183),
	SetAMEM8BitToConst(0x61, 127),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	Jmp(["command_0x3AA833"]),
	ClearAMEM8Bit(0x60, identifier="command_0x3AC373"),
	SetAMEM16BitToConst(0x60, 5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x3A8AAB"]),
	VisibilityOff(unknown_byte=0x01),
	PlaySound(sound=S0107_BUBBLE_POP),
	Jmp(["command_0x3ABA03"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3AC384"),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0482_YARIDOVICH, sequence=0, priority=2, vram_address=0x7800, palette_row=12, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=YARIDOVICHEnemy, position=1, bit_7=True),
	RunSubroutine(["command_0x3A7541"]),
	RunSubroutine(["command_0x3A756A"]),
	ReturnSpriteQueue(),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC3A1"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT, sequence=0, priority=2, vram_address=0x7800, palette_row=12, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=MACHINEMADEEnemy2, position=1, bit_7=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=167, y=103, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	SetAMEM8BitToConst(0x60, 167),
	SetAMEM8BitToConst(0x61, 103),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60, identifier="command_0x3AC3CE"),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	RunSubroutine(["command_0x3A771A"]),
	Jmp(["command_0x3AA75F"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC3DC"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT, sequence=0, priority=2, vram_address=0x7A00, palette_row=12, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=MACHINEMADEEnemy2, position=1, bit_7=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=135, y=119, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	SetAMEM8BitToConst(0x60, 135),
	SetAMEM8BitToConst(0x61, 119),
	Jmp(["command_0x3AC3CE"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC40C"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT, sequence=0, priority=2, vram_address=0x7C00, palette_row=12, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=MACHINEMADEEnemy2, position=1, bit_7=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=231, y=135, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	SetAMEM8BitToConst(0x60, 231),
	SetAMEM8BitToConst(0x61, 135),
	Jmp(["command_0x3AC3CE"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC43C"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RemoveObject(),
	NewSpriteAtCoords(sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT, sequence=0, priority=2, vram_address=0x7E00, palette_row=12, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=MACHINEMADEEnemy2, position=1, bit_7=True),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=199, y=151, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	SetAMEM8BitToConst(0x60, 199),
	SetAMEM8BitToConst(0x61, 151),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	RunSubroutine(["command_0x3A755E"], identifier="command_0x3AC475"),
	Jmp(["command_0x3AA75F"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC47B"),
	ClearAMEM8Bit(0x60),
	SetAMEM16BitToConst(0x60, 5),
	UseObjectQueueAtOffsetWithAMEM60PointerOffset(index=6, destinations=["command_0x3A8AAB"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	VisibilityOn(unknown_byte=0x01),
	Jmp(["command_0x3AA833"]),
	ResetTargetMappingMemory(identifier="command_0x3AC491"),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	VisibilityOff(unknown_byte=0x01, identifier="command_0x3AC49D"),
	Jmp(["command_0x3AA879"]),
	ResetTargetMappingMemory(identifier="command_0x3AC4A2"),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=183, y=127, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A72F8"]),
	VisibilityOff(unknown_byte=0x01),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	Jmp(["command_0x3ABA03"]),
	RemoveObject(identifier="command_0x3AC4B7"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=106, y=92, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0473_TENTACLES_LEFT, sequence=5, priority=2, vram_address=0x7000, palette_row=10, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=TENTACLESEnemy2, position=1, bit_7=True, identifier="command_0x3AC4C9"),
	Jmp(["command_0x3AA75F"]),
	RemoveObject(identifier="command_0x3AC4D0"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=219, y=114, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0465_TENTACLES_RIGHT, sequence=5, priority=2, vram_address=0x7200, palette_row=12, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=TENTACLESEnemy, position=1, bit_7=True, identifier="command_0x3AC4E2"),
	Jmp(["command_0x3AA75F"]),
	RemoveObject(identifier="command_0x3AC4E9"),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=216, y=168, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0465_TENTACLES_RIGHT, sequence=5, priority=2, vram_address=0x7400, palette_row=12, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True, identifier="command_0x3AC4F2"),
	SummonMonster(monster=TENTACLESEnemy, position=1, bit_7=True),
	Jmp(["command_0x3AC475"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC502"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=110, y=80, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0473_TENTACLES_LEFT, sequence=5, priority=2, vram_address=0x7000, palette_row=10, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Jmp(["command_0x3AC4C9"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC51A"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=196, y=80, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0473_TENTACLES_LEFT, sequence=5, priority=2, vram_address=0x7200, palette_row=10, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True, identifier="command_0x3AC526"),
	Jmp(["command_0x3AC4C9"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC532"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=220, y=155, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x3AC4F2"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC541"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=72, end_position=72, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A81CE"]),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 168),
	SetAMEM8BitToConst(0x61, 192),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60, identifier="command_0x3AC571"),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3AC579"),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A7541"]),
	UnknownCommand(bytearray([0x6D])),
	ReturnSpriteQueue(),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC583"),
	Jmp(["command_0x3AC579"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC588"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-137, end_position=-137, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A81E2"]),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 88),
	SetAMEM8BitToConst(0x61, 136),
	Jmp(["command_0x3AC571"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC5BB"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=144, end_position=144, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-81, end_position=-81, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=120, y=192, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 120),
	SetAMEM8BitToConst(0x61, 192),
	Jmp(["command_0x3AC571"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC5F8"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=-65, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=72, end_position=72, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
	ResetObjectMappingMemory(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-65, end_position=-65, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=88, y=176, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	RunSubroutine(["command_0x3A7725"]),
	SetAMEM8BitToConst(0x60, 88),
	SetAMEM8BitToConst(0x61, 176),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3AC673"),
	UnknownCommand(bytearray([0x6D])),
	ReturnSpriteQueue(),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3AC677"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=144, end_position=144, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-145, end_position=-145, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=97, start_position=-2049, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=56, y=160, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7259"]),
	SetAMEM8BitToConst(0x60, 56),
	SetAMEM8BitToConst(0x61, 160),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	RunSubroutine(["command_0x3A7725"]),
	Jmp(["command_0x3AC673"])
])
