# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=1409, expected_beginning=0x3ABBC6, script=[
	RunSubroutine(["command_0x3A775C"], identifier="command_0x3ABBC6"),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0001_MARIO_JUMP_FRONT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SpriteSequence(sequence=9, mirror=True),
	RunSubroutine(["command_0x3A720C"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=1, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A75B2"]),
	RunSubroutine(["command_0x3A7772"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A722A"]),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A777D"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0001_MARIO_JUMP_FRONT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True, bit_7=True),
	RunSubroutine(["command_0x3A8142"]),
	RunSubroutine(["command_0x3A72DD"]),
	RunSubroutine(["command_0x3A819C"]),
	RunSubroutine(["command_0x3A72DD"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=1, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True, bit_7=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	RunSubroutine(["command_0x3A81F6"]),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=7, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0003_MARIO_SURPRISE_LEFT, sequence=4, store_to_vram=True, looping=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_7=True),
	RunSubroutine(["command_0x3A7793"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT, sequence=1, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True, bit_7=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=6, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=6, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A75F0"]),
	RunSubroutine(["command_0x3A77A9"]),
	SpriteSequence(sequence=10, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A7236"]),
	SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3ABCA2"),
	Jmp(["command_0x3AA879"]),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3ABCA7"),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A7200"]),
	DisplayMessage(ATTACK_NAME, 82),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A758E"]),
	RunSubroutine(["command_0x3A7772"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A722A"]),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A7730"]),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A81B0"]),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=1, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	DisplayMessage(ATTACK_NAME, 85),
	SpriteSequence(sequence=4, looping_on=True),
	RunSubroutine(["command_0x3A733C"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75CC"]),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A8192"]),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=10, looping_off=True),
	RunSubroutine(["command_0x3A7788"]),
	DisplayMessage(ATTACK_NAME, 87),
	SpriteSequence(sequence=4, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=4, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	RunSubroutine(["command_0x3A75E4"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=6, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=6, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A77A9"]),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A7236"]),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A77CA"]),
	DisplayMessage(ATTACK_NAME, 90),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A7614"]),
	Jmp(["command_0x3AA879"]),
	RunSubroutine(["command_0x3A7751"], identifier="command_0x3ABD78"),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A7200"]),
	DisplayMessage(ATTACK_NAME, 83),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75A6"]),
	RunSubroutine(["command_0x3A7772"]),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0026_GENO_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A722A"]),
	SpriteSequence(sequence=0, looping_off=True),
	RunSubroutine(["command_0x3A777D"]),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A8174"]),
	RunSubroutine(["command_0x3A7259"]),
	SpriteSequence(sequence=0, looping_off=True),
	DisplayMessage(ATTACK_NAME, 86),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0025_GENO_WALKING_DOWN_LEFT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A75D8"]),
	RunSubroutine(["command_0x3A7793"]),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=7, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=7, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	RunSubroutine(["command_0x3A77A9"]),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	DisplayMessage(ATTACK_NAME, 88),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0026_GENO_WALKING_UP_RIGHT, sequence=3, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	RunSubroutine(["command_0x3A7236"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntilDialogClosed(),
	DisplayMessage(ATTACK_NAME, 89),
	SpriteSequence(sequence=5, looping_off=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A7620"]),
	Jmp(["command_0x3AA879"]),
	ResetTargetMappingMemory(identifier="command_0x3ABDFD"),
	ResetObjectMappingMemory(),
	SetAMEM40ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=-32, y=16, z=0, set_x=True, set_y=True, set_z=True),
	MoveObject(speed=1, start_position=-257, end_position=-257, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=128, end_position=128, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	ResetObjectMappingMemory(),
	DisplayMessage(ATTACK_NAME, 71),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A756A"]),
	RunSubroutine(["command_0x3A7730"]),
	DisplayMessage(ATTACK_NAME, 72),
	SpriteSequence(sequence=5),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=5),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(),
	PauseScriptUntilDialogClosed(identifier="command_0x3ABE30"),
	RunSubroutine(["command_0x3A7582"]),
	Jmp(["command_0x3AA86B"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3ABE37"),
	DisplayMessage(ATTACK_NAME, 81),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT, sequence=9, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_7=True),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=9, mirror=True),
	PauseScriptUntilSpriteSequenceDone(),
	DrawSpriteAtAMEM32Coords(sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT, sequence=0, store_to_vram=True, store_palette=True, behind_all_sprites=True, overlap_all_sprites=True, bit_4=True),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A7576"], identifier="command_0x3ABE4E"),
	RunSubroutine(["command_0x3A773B"]),
	RunSubroutine(["command_0x3A71DA"]),
	ReturnSpriteQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_INITIAL_POSITION, x=0, y=0, z=-256, set_x=True, identifier="command_0x3ABE58"),
	RunSubroutine(["command_0x3A7725"]),
	DisplayMessage(ATTACK_NAME, 63),
	ResetTargetMappingMemory(),
	MoveObject(speed=129, start_position=1024, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A724F"]),
	RunSubroutine(["command_0x3A7576"]),
	MoveObject(speed=129, start_position=-1025, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	PauseScriptUntil(condition=BUTTON_PRESSED),
	ResetObjectMappingMemory(identifier="command_0x3ABE85"),
	Jmp(["command_0x3AAAF7"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=184, y=128, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3ABE89"),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A8584"]),
	RunSubroutine(["command_0x3A725C"]),
	RunSubroutine(["command_0x3A71EE"]),
	SpriteSequence(sequence=1, looping_off=True),
	RunSubroutine(["command_0x3A7730"], identifier="command_0x3ABE9E"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	Jmp(["command_0x3ABCA2"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=184, y=128, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3ABEAE"),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A8570"]),
	RunSubroutine(["command_0x3A725C"]),
	RunSubroutine(["command_0x3A71EE"]),
	SpriteSequence(sequence=1, looping_off=True),
	Jmp(["command_0x3ABE9E"]),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=184, y=128, z=0, set_x=True, set_y=True, set_z=True, identifier="command_0x3ABEC6"),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A855C"]),
	RunSubroutine(["command_0x3A725C"]),
	RunSubroutine(["command_0x3A71EE"]),
	SpriteSequence(sequence=1, looping_off=True),
	RunSubroutine(["command_0x3A756A"]),
	Jmp(["command_0x3ABE9E"]),
	DisplayMessage(ATTACK_NAME, 64, identifier="command_0x3ABEE1"),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A756A"]),
	RunSubroutine(["command_0x3A7730"]),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=170, y=129, z=-48, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7265"]),
	ClearAMEM8Bit(0x60),
	ClearAMEM8Bit(0x61),
	ClearAMEM8Bit(0x62),
	SetAMEM8BitToConst(0x60, 170),
	SetAMEM8BitToConst(0x61, 129),
	SetAMEM8BitToConst(0x62, 48, identifier="command_0x3ABF0C"),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	SetRAMRelative7EToAMEM8Bit(0x7E003D, 0x62),
	Jmp(["command_0x3AA879"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3ABF1F"),
	DisplayMessage(ATTACK_NAME, 66),
	SpriteSequence(sequence=3),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	RunSubroutine(["command_0x3A7576"]),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=168, y=128, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7265"]),
	ClearAMEM8Bit(0x60),
	ClearAMEM8Bit(0x61),
	ClearAMEM8Bit(0x62),
	SetAMEM8BitToConst(0x60, 168),
	SetAMEM8BitToConst(0x61, 128),
	SetAMEM8BitToConst(0x62, 0),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	SetRAMRelative7EToAMEM8Bit(0x7E003D, 0x62),
	Jmp(["command_0x3AA833"]),
	DisplayMessage(ATTACK_NAME, 65, identifier="command_0x3ABF5D"),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A756A"]),
	ClearAMEM8Bit(0x60),
	ClearAMEM8Bit(0x61),
	ClearAMEM8Bit(0x62),
	SetAMEM8BitToConst(0x60, 151),
	SetAMEM8BitToConst(0x61, 119),
	SetAMEM8BitToConst(0x62, 0),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	SetRAMRelative7EToAMEM8Bit(0x7E003D, 0x62),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=151, y=119, z=0, set_x=True, set_y=True, set_z=True),
	RunSubroutine(["command_0x3A7265"], identifier="command_0x3ABF8F"),
	Jmp(["command_0x3AA833"]),
	RunSubroutine(["command_0x3A7725"], identifier="command_0x3ABF95"),
	ClearAMEM8Bit(0x60),
	ClearAMEM8Bit(0x61),
	ClearAMEM8Bit(0x62),
	SetAMEM8BitToConst(0x60, 199),
	SetAMEM8BitToConst(0x61, 143),
	SetAMEM8BitToConst(0x62, 0),
	SetRAMRelative7EToAMEM8Bit(0x7E003B, 0x60),
	SetRAMRelative7EToAMEM8Bit(0x7E003C, 0x61),
	SetRAMRelative7EToAMEM8Bit(0x7E003D, 0x62),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=199, y=143, z=0, set_x=True, set_y=True, set_z=True),
	Jmp(["command_0x3ABF8F"]),
	RunSubroutine(["command_0x3ABFCF"], identifier="command_0x3ABFC2"),
	ReturnSpriteQueue(),
	Jmp(["command_0x3ABFC2"], identifier="command_0x3ABFC6"),
	RunSubroutine(["command_0x3ABFCF"], identifier="command_0x3ABFC9"),
	Jmp(["command_0x3AA833"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3ABFCF"),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=256, end_position=256, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=-129, end_position=-129, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3AC020"]),
	SpriteSequence(sequence=0, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_off=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_off=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
	SpriteSequence(sequence=1, looping_on=True),
	ResetTargetMappingMemory(),
	MoveObject(speed=1, start_position=-1025, end_position=-1025, apply_to_x=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=1, start_position=512, end_position=512, apply_to_y=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
	ResetObjectMappingMemory(),
	ResetTargetMappingMemory(),
	MoveObject(speed=17, start_position=-1025, end_position=0, apply_to_x=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	MoveObject(speed=65, start_position=-1025, end_position=1024, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60, identifier="command_0x3AC020"),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	DisplayMessage(ATTACK_NAME, 91, identifier="command_0x3AC026"),
	RunSubroutine(["command_0x3A721E"]),
	PauseScriptUntilDialogClosed(),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
	DisplayMessage(ATTACK_NAME, 92),
	SpriteSequence(sequence=4),
	PauseScriptUntilSpriteSequenceDone(),
	ResetSpriteSequence(),
	PauseScriptUntilDialogClosed(),
	RunSubroutine(["command_0x3A756A"]),
	RunSubroutine(["command_0x3A7730"]),
	DisplayMessage(ATTACK_NAME, 93),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=2),
	PauseScriptUntilSpriteSequenceDone(),
	SpriteSequence(sequence=3),
	PlaySound(sound=S0004_JUMP),
	RunSubroutine(["command_0x3A7359"]),
	ResetSpriteSequence(),
	PauseScriptUntilDialogClosed(),
	DisplayMessage(ATTACK_NAME, 94),
	RunSubroutine(["command_0x3A733C"]),
	Jmp(["command_0x3ABE30"]),
	RunSubroutine(["command_0x3A773B"], identifier="command_0x3AC05A"),
	RemoveObject(),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=204, y=62, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0331_BANDANA_BLUE, sequence=0, priority=2, vram_address=0x7800, palette_row=12, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	SummonMonster(monster=BANDANABLUEEnemy, position=1, bit_7=True),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=184, y=52, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=96),
	RunSubroutine(["command_0x3A71E9"]),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=154, y=67, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=128),
	PauseScriptUntil(condition=UNKNOWN_PAUSE_1),
	ResetTargetMappingMemory(),
	SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=104, y=112, z=0, set_x=True, set_y=True, set_z=True),
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=352),
	PauseScriptUntil(condition=UNKNOWN_PAUSE_1),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	RunSubroutine(["command_0x3A7359"]),
	UnknownCommand(bytearray([0x16]), identifier="command_0x3AC0B3"),
	Pause1Frame(),
	SetAMEM8BitToAbsolute7E(0x67, 0x7EE003),
	JmpIfAMEMBitsSet(0x67, [0], ["command_0x3AC0F7"]),
	Pause1Frame(),
	SetAMEMToRandomByte(amem=0x68, upper_bound=100),
	JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3AC0DF"]),
	JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3AC0E7"]),
	JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3AC0ED"]),
	JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3AC0F2"]),
	SpriteSequence(sequence=0, looping_off=True, mirror=True, identifier="command_0x3AC0DA"),
	Jmp(["command_0x3AC0B3"]),
	SpriteSequence(sequence=0, looping_on=True, mirror=True, identifier="command_0x3AC0DF"),
	RunSubroutine(["command_0x3A7373"]),
	Jmp(["command_0x3AC0DA"]),
	SpriteSequence(sequence=2, mirror=True, identifier="command_0x3AC0E7"),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x3AC0E9"),
	Jmp(["command_0x3AC0B3"]),
	SpriteSequence(sequence=3, mirror=True, identifier="command_0x3AC0ED"),
	Jmp(["command_0x3AC0E9"]),
	SpriteSequence(sequence=4, mirror=True, identifier="command_0x3AC0F2"),
	Jmp(["command_0x3AC0E9"]),
	Pause1Frame(identifier="command_0x3AC0F7"),
	SpriteSequence(sequence=0, looping_off=True, mirror=True),
	Jmp(["command_0x3AC0F7"])
])
