# pyright: reportWildcardImportFromLibrary=false
from smrpgpatchbuilder.datatypes.battle_animation_scripts import *
from ....variables.sprite_names import *
from ....variables.music_names import *
from ....variables.battle_sfx_names import *
from ....variables.battle_effect_names import *
from ....variables.battle_event_names import *
from ....variables.screen_effect_names import *
from ....spells.spells import *
from ....items.items import *
from ....enemies.enemies import *
from ....enemy_attacks.attacks import *
from smrpgpatchbuilder.datatypes.battle_animation_scripts.arguments.battle_targets import *

script = AnimationScriptBlock(expected_size=488, expected_beginning=0x3A7333, script=[
	MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=384, identifier="command_0x3A7333"),
	Jmp(["command_0x3A71E9"]),
	ResetTargetMappingMemory(identifier="command_0x3A733C"),
	RunSubroutine(["command_0x3A7340"]),
	MoveObject(speed=1, start_position=-769, end_position=-769, apply_to_z=True, should_set_end_position=True, should_set_speed=True, identifier="command_0x3A7340"),
	RunSubroutine(["command_0x3A7353"]),
	MoveObject(speed=1, start_position=768, end_position=768, apply_to_z=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8, identifier="command_0x3A7353"),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x3A7359"),
	MoveObject(speed=81, start_position=-1281, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A736D"]),
	MoveObject(speed=81, start_position=0, end_position=1280, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16, identifier="command_0x3A736D"),
	ResetObjectMappingMemory(),
	ReturnSubroutine(),
	ResetTargetMappingMemory(identifier="command_0x3A7373"),
	MoveObject(speed=129, start_position=-2049, end_position=0, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	RunSubroutine(["command_0x3A736D"]),
	MoveObject(speed=129, start_position=0, end_position=2048, apply_to_z=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	Jmp(["command_0x3A736D"]),
	ResetTargetMappingMemory(identifier="command_0x3A738A"),
	MoveObject(speed=1, start_position=-1025, end_position=-1025, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	ResetObjectMappingMemory(),
	MoveObject(speed=1, start_position=1024, end_position=1024, apply_to_y=True, should_set_start_position=True, should_set_end_position=True, should_set_speed=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
	ResetObjectMappingMemory(),
	SetAMEM8BitToAbsolute7E(0x68, 0x7EE01F),
	JmpIfAMEMBitsClear(0x68, [0], ["command_0x3A738A"]),
	ReturnSubroutine(),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3A73AF"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	RunSubroutine(["command_0x3A73DA"]),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12, identifier="command_0x3A73DA"),
	RunSubroutine(["command_0x3A7359"], identifier="command_0x3A73DE"),
	ReturnSubroutine(),
	SpriteSequence(sequence=1, looping_on=True, mirror=True, identifier="command_0x3A73E2"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True),
	RunSubroutine(["command_0x3A73DA"]),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True),
	Jmp(["command_0x3A73DA"]),
	SpriteSequence(sequence=0, looping_on=True, mirror=True, identifier="command_0x3A7410"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True),
	RunSubroutine(["command_0x3A73DA"]),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	SpriteSequence(sequence=1, looping_on=True),
	Jmp(["command_0x3A73DA"]),
	SpriteSequence(sequence=0, looping_on=True, mirror=True, identifier="command_0x3A743E"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	RunSubroutine(["command_0x3A7359"]),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8, identifier="command_0x3A746D"),
	Jmp(["command_0x3A73DE"]),
	SpriteSequence(sequence=1, looping_on=True, mirror=True, identifier="command_0x3A7474"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	RunSubroutine(["command_0x3A7359"]),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True),
	Jmp(["command_0x3A746D"]),
	SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3A74A6"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	RunSubroutine(["command_0x3A7359"]),
	SpriteSequence(sequence=1, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True, mirror=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=0, looping_on=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
	SpriteSequence(sequence=1, looping_on=True, mirror=True),
	Jmp(["command_0x3A746D"])
])
